_wandb:
    value:
        cli_version: 0.25.1
        e:
            kjurgga6eberazllmu0jk5ncymvlzh70:
                args:
                    - --encoder
                    - vjepa
                    - --FULL
                codePath: src/m07_umap.py
                codePathLocal: src/m07_umap.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "34359738368"
                        used: "3177701376"
                email: kapilw25@gmail.com
                executable: /workspace/factorjepa/venv_walkindia/bin/python
                git:
                    commit: bf645ddc41e5cedf243cd16e499edfdc45d54bc4
                    remote: https://github.com/kapilw25/factorjepa.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-385fd64a-daf1-e235-0f52-ff35f2f5a5dd
                host: 2d5319172a4c
                memory:
                    total: "134098214912"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /workspace/factorjepa/src/m07_umap.py
                python: CPython 3.12.13
                root: /workspace/factorjepa
                startedAt: "2026-04-04T16:46:32.817462Z"
                writerId: kjurgga6eberazllmu0jk5ncymvlzh70
        m: []
        python_version: 3.12.13
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.13
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
FULL:
    value: true
POC:
    value: false
SANITY:
    value: false
encoder:
    value: vjepa
min_dist:
    value: 0.1
n_neighbors:
    value: 15
no_wandb:
    value: false
subset:
    value: null
