"""Shared primitives for V-JEPA training (m09a pretrain / m09b explora / m09c surgery).

Extracted from m09_pretrain.py in Phase 1 of the iter8 split (plan: iter/iter8/plan_code_dev.md).

CRITICAL CONTRACT: every function here is technique-agnostic. NO branches on
argparse flags (explora / surgery) or config technique keys — mode-specific
behavior is configured via explicit parameters (e.g. `init_params=None`,
`drift_cfg=None`, `explora_enabled=False`).
"""
import copy
import csv  # noqa: F401 — retained for future logging helpers
import gc
import glob
import json
import math  # noqa: F401 — retained for future scheduler helpers
import os
import queue
import random  # noqa: F401 — used by callers + reserved for FactorSampler variants
import shutil
import sys
import tempfile
import threading
import time
from pathlib import Path

import numpy as np
import yaml
import torch
import torch.nn.functional as F
from tqdm import tqdm  # noqa: F401 — re-exported for caller convenience

# Absolute imports (work because callers insert src/ on sys.path at import time,
# matching m09_pretrain.py:53 pattern).
from utils.config import get_pipeline_config
from utils.data_download import iter_clips_parallel
from utils.gpu_batch import AdaptiveBatchSizer, cuda_cleanup  # noqa: F401 (AdaptiveBatchSizer re-exported)
from utils.video_io import get_clip_key, create_stream, decode_video_bytes
from utils.vjepa2_imports import (
    get_vit_by_arch, get_vit_predictor, get_vit_predictor_2_1,  # noqa: F401 (re-exported for builders)
    get_mask_generator, get_apply_masks,
)

# ─────────────────────────────────────────────────────────────────────────
# Module constants (extracted from m09_pretrain.py:78-89)
# ─────────────────────────────────────────────────────────────────────────
CHECKPOINT_PREFIX = "m09_ckpt"
_pcfg = get_pipeline_config()
DECODE_WORKERS = _pcfg["streaming"]["decode_workers_train"]
MAX_STREAM_RETRIES = _pcfg["streaming"]["max_retries"]

# Alias used by producer_thread — matches m09_pretrain.py:89
_create_stream = create_stream


# ═════════════════════════════════════════════════════════════════════════
# CONFIG
# ═════════════════════════════════════════════════════════════════════════

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


# ═════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═════════════════════════════════════════════════════════════════════════

def load_val_subset(val_subset_path: str) -> set:
    """Load val subset clip keys from JSON (generated by m00c_sample_subset.py)."""
    if not val_subset_path:
        return set()
    p = Path(val_subset_path)
    if not p.exists():
        print(f"FATAL: Val subset file not found: {p}")
        sys.exit(1)
    with open(p) as f:
        data = json.load(f)
    keys = set(data["clip_keys"])
    print(f"[VAL] Loaded val subset: {len(keys):,} clips from {p.name}")
    return keys


# ImageNet normalization — MUST match Meta's V-JEPA training pipeline.
# deps/vjepa2/app/vjepa/transforms.py line 110: _tensor_normalize_inplace(buffer, mean, std)
# Without this, the model sees [0,1] range during training but [-2,2.6] during evaluation
# (HF processor normalizes). The mismatch caused -26% Prec@K artifact.
IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)


def augment_clip_consistent(video_tensor: torch.Tensor, cfg_aug: dict,
                            crop_size: int) -> torch.Tensor:
    """Video-consistent augmentation matching Meta's V-JEPA pipeline exactly.

    Steps: RandomResizedCrop → HorizontalFlip → ImageNet normalize.
    Matches deps/vjepa2/app/vjepa/transforms.py:VideoTransform.__call__().
    """
    import torchvision.transforms as TT

    T_frames, C, H, W = video_tensor.shape
    scale = cfg_aug["random_resize_scale"]
    ratio = cfg_aug["random_resize_ratio"]

    i, j, h, w = TT.RandomResizedCrop.get_params(
        video_tensor[0], scale=scale, ratio=ratio)

    video = video_tensor.float() / 255.0
    video = video[:, :, i:i+h, j:j+w]
    video = F.interpolate(video, size=(crop_size, crop_size),
                          mode='bilinear', align_corners=False)

    if torch.rand(1).item() < cfg_aug["horizontal_flip"]:
        video = video.flip(-1)

    # ImageNet normalization — matches Meta's training exactly
    video = (video - IMAGENET_MEAN.to(video.device)) / IMAGENET_STD.to(video.device)

    return video  # (T, C, crop_size, crop_size), ImageNet-normalized


def producer_thread(cfg: dict, q: queue.Queue, stop_event: threading.Event,
                    train_keys: set, processed_steps: int):
    """Stream WebDataset, decode videos, augment, enqueue batches (multi-epoch)."""
    from concurrent.futures import ThreadPoolExecutor

    # Prevent ATen thread oversubscription (CLAUDE.md rule #12)
    torch.set_num_threads(1)

    batch_size = cfg["optimization"]["batch_size"]
    num_frames = cfg["data"]["num_frames"]
    crop_size = cfg["data"]["crop_size"]
    local_data = cfg["data"]["local_data"]
    cfg_aug = cfg["augmentation"]
    retries = 0
    epoch = 0

    tmp_dir = tempfile.mkdtemp(prefix="m09_")

    def _decode_batch(pool, pending_bytes, pending_keys):
        """Decode + augment a batch using the shared thread pool."""
        futures = [
            pool.submit(decode_video_bytes, b, tmp_dir, k, num_frames)
            for b, k in zip(pending_bytes, pending_keys)
        ]
        results = [(f.result(), k) for f, k in zip(futures, pending_keys)]

        batch_tensors = [t for t, k in results if t is not None]
        batch_keys = [k for t, k in results if t is not None]

        if batch_tensors:
            augmented = [augment_clip_consistent(vt, cfg_aug, crop_size)
                         for vt in batch_tensors]
            batch = torch.stack(augmented, dim=0).permute(0, 2, 1, 3, 4)
            q.put(("batch", batch, batch_keys[:]))

    try:
        # Single thread pool for entire producer lifetime (avoids thread exhaustion —
        # creating per-batch leaks threads: CPython #98467, ffmpeg spawns 16 internal
        # threads per decoder when thread_count=0)
        with ThreadPoolExecutor(max_workers=DECODE_WORKERS) as pool:
            while not stop_event.is_set():
                try:
                    epoch += 1
                    if epoch > 1:
                        print(f"  Producer: starting epoch {epoch}")
                    pending_bytes, pending_keys = [], []

                    if local_data:
                        # Fast path: parallel TAR readers (8 threads per epoch)
                        clip_q, tar_stop, _reader = iter_clips_parallel(
                            local_data, subset_keys=train_keys or None)
                        while not stop_event.is_set():
                            item = clip_q.get(timeout=120)
                            if item is None:
                                break
                            clip_key, mp4_bytes = item
                            if not mp4_bytes:
                                continue
                            pending_bytes.append(mp4_bytes)
                            pending_keys.append(clip_key)
                            if len(pending_bytes) >= batch_size:
                                _decode_batch(pool, pending_bytes, pending_keys)
                                pending_bytes, pending_keys = [], []
                        tar_stop.set()
                    else:
                        # Fallback: sequential HF streaming
                        ds = _create_stream(0, local_data=local_data)
                        for example in ds:
                            if stop_event.is_set():
                                break
                            clip_key = get_clip_key(example)
                            if train_keys and clip_key not in train_keys:
                                continue
                            mp4_data = example.get("mp4", b"")
                            mp4_bytes = mp4_data["bytes"] if isinstance(mp4_data, dict) else mp4_data
                            if not mp4_bytes:
                                continue
                            pending_bytes.append(mp4_bytes)
                            pending_keys.append(clip_key)
                            if len(pending_bytes) >= batch_size:
                                _decode_batch(pool, pending_bytes, pending_keys)
                                pending_bytes, pending_keys = [], []

                    # Handle final partial batch
                    if pending_bytes and not stop_event.is_set():
                        _decode_batch(pool, pending_bytes, pending_keys)

                    # Loop to next epoch (don't break — training needs multiple passes)

                except (ConnectionError, TimeoutError, OSError) as e:
                    retries += 1
                    if retries > MAX_STREAM_RETRIES:
                        print(f"  FATAL: stream failed after {MAX_STREAM_RETRIES} retries: {e}")
                        break
                    wait = min(2 ** retries, 60)
                    print(f"  Stream error ({e}), retry {retries}/{MAX_STREAM_RETRIES} in {wait}s")
                    time.sleep(wait)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        q.put(("error" if retries > MAX_STREAM_RETRIES else "done", None, None))


# ═════════════════════════════════════════════════════════════════════════
# MASKING (Q4: Use _MaskGenerator directly, not MaskCollator)
# ═════════════════════════════════════════════════════════════════════════

def build_mask_generators(cfg: dict) -> list:
    """Build one _MaskGenerator per mask config."""
    _MaskGenerator = get_mask_generator()

    data_cfg = cfg["data"]
    model_cfg = cfg["model"]  # crop_size/patch_size/tubelet_size live under model: per configs/model/vjepa2_*.yaml (#51)
    generators = []
    for m_cfg in cfg["mask"]:
        mg = _MaskGenerator(
            crop_size=(model_cfg["crop_size"], model_cfg["crop_size"]),
            num_frames=data_cfg["num_frames"],
            spatial_patch_size=(model_cfg["patch_size"], model_cfg["patch_size"]),
            temporal_patch_size=model_cfg["tubelet_size"],
            spatial_pred_mask_scale=m_cfg["spatial_scale"],
            temporal_pred_mask_scale=m_cfg["temporal_scale"],
            aspect_ratio=m_cfg["aspect_ratio"],
            npred=m_cfg["num_blocks"],
        )
        generators.append(mg)
    return generators


# ═════════════════════════════════════════════════════════════════════════
# LOSS (L1 latent prediction + drift control)
# ═════════════════════════════════════════════════════════════════════════

def compute_jepa_loss(pred_features: list, pred_context: list,
                      teacher_output: torch.Tensor,
                      masks_pred: list, masks_enc: list,
                      loss_exp: float, predict_all: bool,
                      lambda_context: float = 0.5) -> tuple:
    """V-JEPA 2.1 dense loss: masked tokens + context tokens.

    When predict_all=True (V-JEPA 2.1), computes loss on ALL tokens:
    - Masked loss: predictor output vs teacher at masked positions
    - Context loss: predictor context output vs teacher at visible positions
    - Total = masked_loss + lambda_context * context_loss

    Returns (total_loss, loss_masked, loss_context).
    """
    apply_masks = get_apply_masks()

    # Masked token loss
    loss_masked = torch.tensor(0.0, device=teacher_output.device)
    n = 0
    for pred_i, mask_i in zip(pred_features, masks_pred):
        h_masked = apply_masks(teacher_output, [mask_i])
        loss_masked += torch.mean(torch.abs(pred_i - h_masked) ** loss_exp) / loss_exp
        n += 1
    loss_masked = loss_masked / max(n, 1)

    # Context token loss (V-JEPA 2.1 dense loss — doubles training signal)
    loss_context = torch.tensor(0.0, device=teacher_output.device)
    if predict_all and pred_context:
        n_ctx = 0
        for ctx_i, mask_enc_i in zip(pred_context, masks_enc):
            if ctx_i is None:
                continue
            h_context = apply_masks(teacher_output, [mask_enc_i])
            loss_context += torch.mean(torch.abs(ctx_i - h_context) ** loss_exp) / loss_exp
            n_ctx += 1
        loss_context = loss_context / max(n_ctx, 1)

    total = loss_masked + lambda_context * loss_context
    return total, loss_masked, loss_context


def compute_drift_loss(student: torch.nn.Module, init_params: dict,
                       lambda_reg: float) -> torch.Tensor:
    """L2 drift control: lambda * ||theta - theta_0||^2 (Sec 10.4)."""
    device = next(student.parameters()).device
    drift = torch.tensor(0.0, device=device)
    for name, param in student.named_parameters():
        if name in init_params:
            drift += torch.sum((param - init_params[name].to(device)) ** 2)
    return lambda_reg * drift


def _train_step_grad_accum(student, teacher, predictor, batch_clips,
                           all_masks_enc, all_masks_pred,
                           cfg, dtype, mp_cfg, scaler, sizer, loss_exp,
                           init_params=None, drift_cfg=None):
    """Forward+backward with adaptive micro-batch sizing + gradient accumulation (#48).

    Splits the macro batch into micro-batches of `sizer.size`, runs forward+backward
    per micro, scales each micro's loss by (micro_size / macro_size) so accumulated
    gradients are mathematically identical to a single full-batch step. The optimizer
    step + zero_grad happen ONCE per macro in the caller — preserving effective batch
    size, optimizer dynamics (Adam momentum, weight-decay scheduling, LR scaling),
    and convergence behavior. Only the GPU memory footprint shrinks.

    Drift loss (parameter regularizer, no batch dim) is added once after the micro
    loop with full weight — equivalent to a single-batch step.

    Returns (jepa_val, masked_val, context_val, drift_val) — running totals
    weighted to match macro-batch mean (interpretable for logging).

    On OOM: cuda_cleanup + sizer.on_oom + raises — caller calls optimizer.zero_grad()
    to discard partial gradients and retries on the next producer batch.
    """
    embed_dim = cfg["model"]["embed_dim"]
    n_levels = cfg["model"]["n_output_distillation"]
    predict_all = cfg["model"]["predict_all"]
    macro_bs = batch_clips.shape[0]

    j_val, m_val, c_val = 0.0, 0.0, 0.0
    i = 0
    while i < macro_bs:
        end = min(i + sizer.size, macro_bs)
        micro_bs = end - i
        weight = micro_bs / macro_bs

        bc = batch_clips[i:end]
        m_enc_list = [m[i:end] for m in all_masks_enc]
        m_pred_list = [m[i:end] for m in all_masks_pred]

        try:
            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                with torch.no_grad():
                    h = teacher(bc)
                    if h.size(-1) == n_levels * embed_dim:
                        chunks = [F.layer_norm(h[:, :, lvl * embed_dim:(lvl + 1) * embed_dim],
                                               (embed_dim,))
                                  for lvl in range(n_levels)]
                        h = torch.cat(chunks, dim=2)
                    else:
                        h = F.layer_norm(h, (h.size(-1),))
                pf, pc = [], []
                for k, (me, mp) in enumerate(zip(m_enc_list, m_pred_list)):
                    z = student(bc, masks=[me])
                    out = predictor(z, [me], [mp], mask_index=k)
                    if isinstance(out, tuple) and len(out) == 2:
                        pf.append(out[0]); pc.append(out[1])
                    else:
                        pf.append(out)
                jl, lm, lc = compute_jepa_loss(pf, pc, h, m_pred_list, m_enc_list,
                                                loss_exp, predict_all, lambda_context=0.5)
            scaler.scale(jl * weight).backward()
        except torch.cuda.OutOfMemoryError:
            cuda_cleanup()
            sizer.on_oom()
            raise

        j_val += jl.item() * weight
        m_val += lm.item() * weight
        c_val += lc.item() * weight
        i = end

    drift_val = 0.0
    if init_params is not None and drift_cfg is not None \
            and drift_cfg.get("enabled") and drift_cfg.get("lambda_reg", 0) > 0:
        drift_loss = compute_drift_loss(student, init_params, drift_cfg["lambda_reg"])
        scaler.scale(drift_loss).backward()
        drift_val = drift_loss.item()

    sizer.after_batch_success()
    return j_val, m_val, c_val, drift_val


# ═════════════════════════════════════════════════════════════════════════
# EMA TEACHER UPDATE
# ═════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def update_teacher_ema(student: torch.nn.Module, teacher: torch.nn.Module,
                       momentum: float):
    """EMA update: theta_bar <- tau * theta_bar + (1-tau) * theta.

    Uses name-based matching so ExPLoRA LoRA params (which only exist in student,
    not teacher) are safely skipped.
    """
    student_dict = dict(student.named_parameters())
    for name, param_t in teacher.named_parameters():
        if name in student_dict:
            param_t.mul_(momentum).add_(student_dict[name].data, alpha=1.0 - momentum)


# ═════════════════════════════════════════════════════════════════════════
# OPTIMIZER & SCHEDULER
# ═════════════════════════════════════════════════════════════════════════

def build_optimizer(student, predictor, cfg_opt: dict):
    """Build AdamW optimizer. Reads `use_8bit_optim` flag (#56) — when True, uses
    bitsandbytes `AdamW8bit` for 4× optimizer-state memory reduction (m1+m2 stored
    as 8-bit block-wise quantized values instead of fp32). <1% accuracy loss per
    Dettmers et al. 2022 ("8-bit Optimizers via Block-wise Quantization",
    arXiv:2110.02861). Standard in HF Trainer (`optim="adamw_bnb_8bit"`) and FAIR
    fairscale for fine-tuning 2B+ models on consumer GPUs.
    """
    base_lr = cfg_opt["lr"]
    pred_lr = base_lr * cfg_opt["pred_lr_multiplier"]
    wd = cfg_opt["weight_decay"]
    use_8bit = cfg_opt["use_8bit_optim"]

    def split_params(module, lr):
        decay, no_decay = [], []
        for name, p in module.named_parameters():
            if not p.requires_grad:
                continue
            if "bias" in name or "norm" in name or "ln" in name:
                no_decay.append(p)
            else:
                decay.append(p)
        return [
            {"params": decay, "lr": lr, "weight_decay": wd},
            {"params": no_decay, "lr": lr, "weight_decay": 0.0},
        ]

    param_groups = split_params(student, base_lr) + split_params(predictor, pred_lr)

    if use_8bit:
        import bitsandbytes as bnb
        # Paged variant (#58) — auto CPU paging of optimizer state on GPU pressure.
        # ONLY read `paged_optim` inside this branch so non-8bit configs (m09a/m09b,
        # m09c POC/FULL) never require the key in their yaml. HF QLoRA standard for
        # fine-tuning 7-65B models on 24-48 GB consumer GPUs.
        paged_optim = cfg_opt["paged_optim"]
        if paged_optim:
            opt = bnb.optim.PagedAdamW8bit(param_groups,
                                             betas=tuple(cfg_opt["betas"]),
                                             eps=cfg_opt["eps"])
            optim_name = "PagedAdamW8bit (bitsandbytes, unified-memory CPU paging)"
        else:
            opt = bnb.optim.AdamW8bit(param_groups,
                                       betas=tuple(cfg_opt["betas"]),
                                       eps=cfg_opt["eps"])
            optim_name = "AdamW8bit (bitsandbytes)"
        n_trainable = sum(len(g["params"]) for g in param_groups)
        print(f"  Optimizer: {optim_name} — {n_trainable} param groups, "
              f"8-bit block-wise quantized m1/m2 (4× memory reduction)")
        return opt
    return torch.optim.AdamW(param_groups, betas=tuple(cfg_opt["betas"]),
                              eps=cfg_opt["eps"])


def enable_gradient_checkpointing(model):
    """Wrap each transformer block's forward in `torch.utils.checkpoint.checkpoint`
    for activation-memory savings (#56). Activations recomputed during backward
    instead of stored → ~2-4× reduction in activation memory at cost of ~25-30%
    throughput (one extra forward pass per block during backward).

    Uses `use_reentrant=False` (modern PyTorch API, required for torch.compile
    compatibility + proper handling of keyword args — V-JEPA blocks accept
    `mask`, `T`, `H_patches`, `W_patches`, `return_attn`, `mode` as kwargs).

    Works for BOTH trainable and frozen blocks — frozen blocks still consume
    activation memory during forward (autograd needs them to backprop gradient
    to earlier trainable blocks), so checkpointing helps regardless of
    `requires_grad`. Gold-standard pattern used by HF Transformers
    `gradient_checkpointing_enable()` and FAIR vissl's checkpoint_wrapper.

    Must be called AFTER model.train() is set and BEFORE build_optimizer —
    safe to call once per stage (idempotent via `_gradient_checkpointing` attr).
    """
    if getattr(model, "_gradient_checkpointing", False):
        return  # idempotent — already wrapped
    if not hasattr(model, "blocks"):
        raise ValueError(f"enable_gradient_checkpointing: model {type(model).__name__} "
                         f"has no .blocks attribute (expected nn.ModuleList)")

    import torch.utils.checkpoint as ckpt

    def make_ckpt_wrapper(original_forward):
        def checkpointed_forward(*args, **kwargs):
            return ckpt.checkpoint(original_forward, *args,
                                   use_reentrant=False, **kwargs)
        return checkpointed_forward

    for block in model.blocks:
        block.forward = make_ckpt_wrapper(block.forward)

    model._gradient_checkpointing = True
    print(f"  Gradient checkpointing enabled on {len(model.blocks)} blocks "
          f"(~2-4× activation memory reduction, ~25% throughput cost)")


def build_scheduler(optimizer, cfg_opt: dict, total_steps: int):
    # Cap warmup to 10% of total steps (avoids never leaving warmup on short runs)
    warmup_cap_pct = cfg_opt["warmup_cap_pct"]
    warmup_steps = min(cfg_opt["warmup_steps"], max(1, total_steps * warmup_cap_pct // 100))
    min_lr = cfg_opt["min_lr"]
    base_lr = cfg_opt["lr"]

    def lr_lambda(step):
        if step < warmup_steps:
            return step / max(warmup_steps, 1)
        progress = (step - warmup_steps) / max(total_steps - warmup_steps, 1)
        return max(min_lr / base_lr, 0.5 * (1 + np.cos(np.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


def update_weight_decay(optimizer, cfg_opt: dict, step: int, total_steps: int):
    """Cosine weight decay schedule (matches Meta's CosineWDSchedule).

    Ramps WD from weight_decay to final_weight_decay over training.
    If both are equal (default: 0.04), this is a no-op.
    """
    initial_wd = cfg_opt["weight_decay"]
    final_wd = cfg_opt["final_weight_decay"]
    if initial_wd == final_wd:
        return  # no-op: fixed WD
    progress = step / max(total_steps, 1)
    new_wd = final_wd + 0.5 * (initial_wd - final_wd) * (1 + np.cos(np.pi * progress))
    for group in optimizer.param_groups:
        if group.get("weight_decay", 0) > 0:  # don't touch no_decay groups
            group["weight_decay"] = new_wd


# ═════════════════════════════════════════════════════════════════════════
# VALIDATION (JEPA L1 loss on held-out val clips)
# ═════════════════════════════════════════════════════════════════════════

def run_validation(student, teacher, predictor, mask_generators,
                   val_batches: list, cfg: dict, device: torch.device,
                   step: int) -> float:
    """Compute JEPA L1 loss on val clips. Same as training loss, different data.

    Returns mean val loss (scalar).
    """
    student.eval()
    predictor.eval()

    mp_cfg = cfg["mixed_precision"]
    dtype = getattr(torch, mp_cfg["dtype"])
    loss_exp = cfg["optimization"]["loss_exp"]
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch_clips in val_batches:
            batch_clips = batch_clips.to(device)
            actual_bs = batch_clips.shape[0]

            # Generate masks (same as training)
            all_masks_enc, all_masks_pred = [], []
            for mg in mask_generators:
                m_enc, m_pred = mg(actual_bs)
                all_masks_enc.append(m_enc.to(device))
                all_masks_pred.append(m_pred.to(device))

            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                # Teacher: all tokens + per-chunk LayerNorm (deep supervision)
                embed_dim_val = cfg["model"]["embed_dim"]
                n_levels_val = cfg["model"]["n_output_distillation"]
                h = teacher(batch_clips)
                if h.size(-1) == n_levels_val * embed_dim_val:
                    chunks = []
                    for lvl in range(n_levels_val):
                        chunk = h[:, :, lvl * embed_dim_val : (lvl + 1) * embed_dim_val]
                        chunks.append(F.layer_norm(chunk, (embed_dim_val,)))
                    h = torch.cat(chunks, dim=2)
                else:
                    h = F.layer_norm(h, (h.size(-1),))

                # Student + Predictor per mask generator
                predict_all_val = cfg["model"]["predict_all"]
                pred_features = []
                pred_context_val = []
                for i, (m_enc, m_pred) in enumerate(zip(all_masks_enc, all_masks_pred)):
                    z = student(batch_clips, masks=[m_enc])
                    outputs = predictor(z, [m_enc], [m_pred], mask_index=i)
                    if isinstance(outputs, tuple) and len(outputs) == 2:
                        pred_features.append(outputs[0])
                        pred_context_val.append(outputs[1])
                    else:
                        pred_features.append(outputs)

                # Dense loss (same as training, no drift control)
                jepa_loss, _, _ = compute_jepa_loss(
                    pred_features, pred_context_val, h,
                    all_masks_pred, all_masks_enc,
                    loss_exp, predict_all_val, lambda_context=0.5)

            total_loss += jepa_loss.item()
            n_batches += 1

    val_loss = total_loss / max(n_batches, 1)
    print(f"  Step {step} | Val JEPA loss: {val_loss:.4f} ({len(val_batches)} batches)")

    student.train()
    predictor.train()
    return val_loss


# ═════════════════════════════════════════════════════════════════════════
# CHECKPOINT
# ═════════════════════════════════════════════════════════════════════════

def save_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler,
                              step: int, best_metric: float,
                              full: bool = True):
    """Save checkpoint. full=True includes optimizer (for resume), False is light (for selection)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(".tmp")
    ckpt = {
        "student": student.state_dict(),
        "teacher": teacher.state_dict(),
        "predictor": predictor.state_dict(),
        "step": step,
        "best_metric": best_metric,
    }
    if full:
        ckpt["optimizer"] = optimizer.state_dict()
        ckpt["scheduler"] = scheduler.state_dict()
        ckpt["scaler"] = scaler.state_dict() if scaler else None
    torch.save(ckpt, tmp_path)
    os.replace(tmp_path, path)


def cleanup_old_checkpoints(output_dir: Path, keep_n: int = 2):
    """Delete oldest m09_ckpt_step*.pt files, keeping only the last keep_n."""
    pattern = str(output_dir / f"{CHECKPOINT_PREFIX}_step*.pt")
    step_files = sorted(glob.glob(pattern),
                        key=lambda f: os.path.getmtime(f))
    if len(step_files) > keep_n:
        for old_file in step_files[:-keep_n]:
            os.remove(old_file)
            print(f"  Cleaned old checkpoint: {Path(old_file).name}")


def load_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler) -> tuple:
    ckpt = torch.load(path, map_location="cuda", weights_only=False)
    student.load_state_dict(ckpt["student"])
    teacher.load_state_dict(ckpt["teacher"])
    predictor.load_state_dict(ckpt["predictor"])
    if "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    if "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    if scaler and ckpt.get("scaler"):
        scaler.load_state_dict(ckpt["scaler"])
    return ckpt["step"], ckpt.get("best_metric", float("inf"))


def export_student_for_eval(student, path: Path, explora_enabled: bool = False):
    """Export student encoder weights + metadata for m05/m06 re-evaluation."""
    from utils.config import VJEPA_MODEL_ID
    path.parent.mkdir(parents=True, exist_ok=True)
    # ExPLoRA: merge LoRA weights into base model before saving
    export_model = student
    if explora_enabled and hasattr(student, "merge_and_unload"):
        print("  Merging LoRA weights into base model for export...")
        export_model = student.merge_and_unload()
    torch.save({
        "student_state_dict": export_model.state_dict(),
        "model_id": VJEPA_MODEL_ID,
        "type": "vjepa2_adapted",
    }, path)
    print(f"Exported student encoder: {path}")


# ═════════════════════════════════════════════════════════════════════════
# SURGERY HELPERS (Ch11 — progressive prefix unfreezing + factor datasets)
# ═════════════════════════════════════════════════════════════════════════

def set_trainable_prefix(student, n_layers: int):
    """Freeze all blocks, then unfreeze blocks [0, n_layers). Rebuild optimizer after calling."""
    for param in student.parameters():
        param.requires_grad = False
    for i in range(min(n_layers, len(student.blocks))):
        for param in student.blocks[i].parameters():
            param.requires_grad = True
    for name, param in student.named_parameters():
        if "norm" in name or "ln" in name:
            param.requires_grad = True
    trainable = sum(p.numel() for p in student.parameters() if p.requires_grad)
    total = sum(p.numel() for p in student.parameters())
    print(f"  Trainable prefix: {n_layers}/{len(student.blocks)} blocks "
          f"({trainable:,}/{total:,} = {100*trainable/total:.1f}%)")


def build_factor_index(manifest: dict, dl_dir: Path, da_dir: Path, di_dir: Path) -> dict:
    """Build clip_key → {D_L: path, D_A: path, D_I: [paths]} from m11 manifest."""
    index = {}
    for clip_key, info in manifest.items():
        safe_key = clip_key.replace("/", "__")
        entry = {}
        if info["has_D_L"]:
            p = dl_dir / f"{safe_key}.npy"
            if p.exists():
                entry["D_L"] = p
        if info["has_D_A"]:
            p = da_dir / f"{safe_key}.npy"
            if p.exists():
                entry["D_A"] = p
        if info.get("has_D_I") and info.get("n_interaction_tubes", 0) > 0:
            tubes = sorted(di_dir.glob(f"{safe_key}_tube*.npy"))
            if tubes:
                entry["D_I"] = tubes
        if entry:
            index[clip_key] = entry
    print(f"  Factor index: {len(index)} clips "
          f"(D_L={sum(1 for e in index.values() if 'D_L' in e)}, "
          f"D_A={sum(1 for e in index.values() if 'D_A' in e)}, "
          f"D_I={sum(1 for e in index.values() if 'D_I' in e)})")
    return index


class FactorSampler:
    """Sample factor clips according to per-stage mode mixture weights."""

    def __init__(self, factor_index: dict, mode_mixture: dict):
        factor_map = {"L": "D_L", "A": "D_A", "I": "D_I"}
        self.clips_by_factor = {}
        for fk in ["D_L", "D_A", "D_I"]:
            self.clips_by_factor[fk] = [
                (key, entry[fk])
                for key, entry in factor_index.items()
                if fk in entry
            ]
        self.factors = []
        self.weights = []
        for mode_key, weight in mode_mixture.items():
            if weight > 0:
                fk = factor_map[mode_key]
                if self.clips_by_factor[fk]:
                    self.factors.append(fk)
                    self.weights.append(weight)
        if not self.factors:
            print("FATAL: No factor clips available for the given mode mixture")
            sys.exit(1)
        total_w = sum(self.weights)
        self.weights = [w / total_w for w in self.weights]
        print(f"  FactorSampler: {', '.join(f'{f}={w:.0%}' for f, w in zip(self.factors, self.weights))}")

    def sample(self) -> tuple:
        """Returns (factor_type, clip_key, path_or_paths)."""
        factor = np.random.choice(self.factors, p=self.weights)
        clips = self.clips_by_factor[factor]
        idx = np.random.randint(len(clips))
        clip_key, path = clips[idx]
        if isinstance(path, list):
            path = path[np.random.randint(len(path))]
        return factor, clip_key, path


# ═════════════════════════════════════════════════════════════════════════
# MID-TRAINING PROBE EVAL (Prec@K / mAP@K / Cycle@K with BCa 95% CI)
# ═════════════════════════════════════════════════════════════════════════
#
# Purpose: at stage boundaries, embed a held-out probe set through the CURRENT
# student and compute the same retrieval metrics the D.4 decision gate uses.
# Watches Surgery > Frozen emerge (or not) across the 3 stages without waiting
# for the full m05+m06 re-run cycle.
#
# Contract (technique-agnostic):
#   - Input:  student (vjepa2 VisionTransformer), pre-decoded probe tensors,
#             cfg dict, device.
#   - Output: dict with {prec_at_k, map_at_k, cycle_at_k} each {mean, ci_half}
#             and num_clips.
#   - No persistent state mutation: train()/eval() + return_hierarchical toggled
#     then restored under try/finally so the stage loop continues cleanly.
#
# Pooling matches m05_vjepa_embed.py:242 (outputs.mean(dim=1) over patch dim).
# Deterministic preprocess (center-crop + ImageNet-norm, no aug) so mid-stage
# deltas track the encoder, not the augmentation RNG.


def _probe_preprocess(video_uint8: torch.Tensor, crop_size: int) -> torch.Tensor:
    """Deterministic probe pipeline: center-crop → resize → ImageNet-normalize.

    video_uint8: (T, C, H, W) uint8 from decode_video_bytes().
    Returns: (T, C, crop_size, crop_size) float32, ImageNet-normalized.
    """
    _, _, H, W = video_uint8.shape
    side = min(H, W)
    top = (H - side) // 2
    left = (W - side) // 2
    video = video_uint8[:, :, top:top + side, left:left + side].float() / 255.0
    video = F.interpolate(video, size=(crop_size, crop_size),
                          mode="bilinear", align_corners=False)
    return (video - IMAGENET_MEAN.to(video.device)) / IMAGENET_STD.to(video.device)


def build_probe_clips(probe_subset_path: str, probe_local_data: str,
                      probe_tags_path: str, num_frames: int, crop_size: int) -> list:
    """Decode + preprocess probe clips ONCE upfront. Returns list of
    (clip_key, tag_dict, tensor[T,C,H,W]).

    Tag alignment: Path(clip_key).name == tag["source_file"]. Clips without a
    matching tag record are skipped (not fatal — probe is best-effort signal).
    Heavy: 1K val_1k clips take ~5-10 min to decode via PyAV. Cost amortized
    across 3 stage-boundary calls.
    """
    subset_keys = set(json.load(open(probe_subset_path))["clip_keys"])
    tags_list = json.load(open(probe_tags_path))
    # Fail-loud: tag records without "source_file" are malformed — skip with explicit test, no .get default.
    tag_by_source = {t["source_file"]: t for t in tags_list if "source_file" in t}

    tmp_dir = tempfile.mkdtemp(prefix="probe_decode_")
    clips = []
    n_no_tag = 0
    try:
        clip_q, tar_stop, _reader = iter_clips_parallel(probe_local_data, subset_keys=subset_keys)
        while True:
            try:
                item = clip_q.get(timeout=120)
            except queue.Empty:
                break
            if item is None:
                break
            clip_key, mp4_bytes = item
            if not mp4_bytes:
                continue
            source_file = Path(clip_key).name
            if source_file not in tag_by_source:
                n_no_tag += 1
                continue
            tag = tag_by_source[source_file]
            video_u8 = decode_video_bytes(mp4_bytes, tmp_dir, clip_key, num_frames)
            if video_u8 is None:
                continue
            tensor = _probe_preprocess(video_u8, crop_size)
            clips.append((clip_key, tag, tensor))
        tar_stop.set()
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print(f"  [probe] decoded {len(clips)} clips ({n_no_tag} skipped — no tag match)")
    if len(clips) < 100:
        print(f"  WARNING: probe has only {len(clips)} clips — bootstrap CI will be wide (N<100)")
    return clips


@torch.no_grad()
def run_probe_eval(student, probe_clips: list, cfg: dict, device: torch.device,
                   k: int, bootstrap_iter: int) -> dict:
    """Embed probe clips → Prec@K / mAP@K / Cycle@K with BCa 95% CI.

    Reuses utils.bootstrap vectorized per-clip functions so numbers are
    directly comparable to the D.4 decision gate (modulo deterministic probe
    preprocessing vs m05's augmented val-time transforms).

    Forward micro-batching: AdaptiveBatchSizer wired per CLAUDE.md B35 +
    errors_N_fixes.md #47 (universal infra, no hardcoded sub_batch). Sizer
    params come from pipeline.yaml — same keys m05 uses:
      - initial_size = gpu.inference_vjepa_initial_bs (safe start)
      - max_size     = gpu.inference_adapted_bs (cap — guards CPU queue + recompile)
      - memory_cap   = gpu.gpu_memory_target (universal 0.85)
    Forward-only (@torch.no_grad), so OOM recovery is clean: shrink → retry
    same micro, no partial-grad state to discard.

    Pooling matches m05:242 — outputs.mean(dim=1) over patch dim → (B, D=1664).
    Returns {"prec_at_k": {mean, ci_half, ci_lo, ci_hi}, ..., "num_clips": N}.
    """
    from utils.bootstrap import (
        bootstrap_ci, encode_tags_to_labels,
        per_clip_prec_at_k, per_clip_map_at_k, per_clip_cycle_at_k,
    )

    n = len(probe_clips)
    if n < 10:
        # Fail-loud: stable BCa CI needs N>=10. Caller wraps in try/except and
        # logs a WARN. Previously returned a dict with None values — that let
        # trajectory stats silently degrade. No defaults, no fallback.
        raise ValueError(
            f"probe N={n} too small for stable 95% BCa CI (needs N>=10). "
            f"Check probe.subset JSON clip_keys list + probe.local_data TAR coverage."
        )

    _gpu = get_pipeline_config()["gpu"]
    sizer = AdaptiveBatchSizer(
        initial_size=_gpu["inference_vjepa_initial_bs"],
        min_size=1,
        max_size=_gpu["inference_adapted_bs"],
        memory_cap=_gpu["gpu_memory_target"],
    )
    print(f"  [probe] AdaptiveBatchSizer: start={sizer.size}, "
          f"max={sizer.max_size}, cap={sizer.memory_cap:.0%}")

    was_training = student.training
    had_hier = getattr(student, "return_hierarchical", None)
    student.eval()
    if had_hier is not None:
        student.return_hierarchical = False

    try:
        model_dtype = next(student.parameters()).dtype
        tags = [t for _, t, _ in probe_clips]
        emb_list = []
        i = 0
        while i < n:
            end = min(i + sizer.size, n)
            batch = torch.stack([c for _, _, c in probe_clips[i:end]])
            batch = batch.permute(0, 2, 1, 3, 4).to(device=device, dtype=model_dtype)
            try:
                out = student(batch)
                emb_list.append(out.mean(dim=1).float().cpu().numpy())
                sizer.after_batch_success()
                i = end
            except torch.cuda.OutOfMemoryError:
                cuda_cleanup()
                if not sizer.on_oom():
                    raise RuntimeError(
                        f"Probe OOM at min sub-batch={sizer.min_size} (N={n}). "
                        f"Student + activations don't fit even at BS=1 on this GPU. "
                        f"Reduce inference_vjepa_initial_bs in pipeline.yaml or run "
                        f"probe on larger hardware."
                    ) from None
                # retry same i at shrunken sizer.size
        embeddings = np.concatenate(emb_list, axis=0)
    finally:
        if had_hier is not None:
            student.return_hierarchical = had_hier
        if was_training:
            student.train()

    # L2-normalize: FAISS IndexFlatL2 on normalized vecs ≡ cosine rank.
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True) + 1e-8
    embeddings = (embeddings / norms).astype(np.float32)

    # N=1K: IndexFlatL2 is exact + fastest; skip IVF. CPU index fine for this size.
    import faiss
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)
    _D, I = index.search(embeddings, k + 1)  # col 0 = self

    label_arrays = encode_tags_to_labels(tags, ["scene_type"])
    prec_scores = per_clip_prec_at_k(I, tags, k, field="scene_type", label_arrays=label_arrays)
    map_scores = per_clip_map_at_k(I, tags, k, field="scene_type", label_arrays=label_arrays) * 100
    cycle_scores = per_clip_cycle_at_k(I, k) * 100

    return {
        "num_clips": n,
        "prec_at_k": bootstrap_ci(prec_scores, n_boot=bootstrap_iter),
        "map_at_k": bootstrap_ci(map_scores, n_boot=bootstrap_iter),
        "cycle_at_k": bootstrap_ci(cycle_scores, n_boot=bootstrap_iter),
    }


def compute_trajectory_stats(probe_history: list) -> dict:
    """Trajectory stats across stage boundaries.

    Single-probe-set regime: BWT degenerates to net improvement R[-1]-R[0] on
    Prec@K. Real GEM-BWT (per-task eval) would need separate D_L/D_A/D_I probe
    splits — deferred as future extension; this already flags regressions.

    Forgetting monitor: max_drop > 0 means some stage transition DROPPED Prec@K
    despite replay → the paper claim "replay prevents forgetting" fails on this
    run. User should inspect per-stage mode_mixture / warmup_pct.
    """
    # Fail-loud on structural issues — every probe_history entry must have the
    # full metric dict (run_probe_eval always returns it; missing = bug upstream).
    # Empty / single-entry history is a legit no-trajectory case (returns empty).
    if len(probe_history) < 2:
        return {"bwt_prec_at_k": None, "monotonic": None, "trajectory": []}

    traj = [r["prec_at_k"]["mean"] for r in probe_history]
    deltas = [traj[i] - traj[i - 1] for i in range(1, len(traj))]
    max_drop = -min(deltas) if min(deltas) < 0 else 0.0
    return {
        "bwt_prec_at_k": round(traj[-1] - traj[0], 4),
        "max_drop_prec_at_k": round(max_drop, 4),
        "monotonic": all(d >= 0 for d in deltas),
        "trajectory": [round(v, 4) for v in traj],
    }


def load_factor_clip(path: Path, num_frames: int, crop_size: int) -> torch.Tensor:
    """Load factor-patched clip from .npy → (T, C, H, W) float32 tensor, ImageNet-normalized."""
    frames = np.load(path)
    if frames.shape[1] != crop_size or frames.shape[2] != crop_size:
        from PIL import Image as _PILResize
        resized = []
        for t in range(frames.shape[0]):
            img = _PILResize.fromarray(frames[t])
            img = img.resize((crop_size, crop_size), _PILResize.BILINEAR)
            resized.append(np.array(img))
        frames = np.stack(resized)
    if frames.shape[0] > num_frames:
        indices = np.linspace(0, frames.shape[0] - 1, num_frames, dtype=int)
        frames = frames[indices]
    elif frames.shape[0] < num_frames:
        pad = np.repeat(frames[-1:], num_frames - frames.shape[0], axis=0)
        frames = np.concatenate([frames, pad], axis=0)
    tensor = torch.from_numpy(frames).permute(0, 3, 1, 2).float() / 255.0
    mean = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
    std = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)
    tensor = (tensor - mean) / std
    return tensor
