"""Shared primitives for V-JEPA training (m09a pretrain / m09b explora / m09c surgery).

Extracted from m09_pretrain.py in Phase 1 of the iter8 split (plan: iter/iter8/plan_code_dev.md).

CRITICAL CONTRACT: every function here is technique-agnostic. NO branches on
argparse flags (explora / surgery) or config technique keys — mode-specific
behavior is configured via explicit parameters (e.g. `init_params=None`,
`drift_cfg=None`, `explora_enabled=False`).
"""
import copy
import csv  # noqa: F401 — retained for future logging helpers
import gc
import glob
import json
import math  # noqa: F401 — retained for future scheduler helpers
import os
import queue
import random  # noqa: F401 — used by callers + reserved for FactorSampler variants
import shutil
import sys
import tempfile
import threading
import time
from pathlib import Path

import numpy as np
import yaml
import torch
import torch.nn.functional as F
from tqdm import tqdm  # noqa: F401 — re-exported for caller convenience

# Absolute imports (work because callers insert src/ on sys.path at import time,
# matching m09_pretrain.py:53 pattern).
from utils.config import get_pipeline_config
from utils.data_download import iter_clips_parallel
from utils.gpu_batch import AdaptiveBatchSizer, cuda_cleanup  # noqa: F401 (AdaptiveBatchSizer re-exported)
from utils.video_io import get_clip_key, create_stream, decode_video_bytes
from utils.vjepa2_imports import (
    get_vit_by_arch, get_vit_predictor, get_vit_predictor_2_1,  # noqa: F401 (re-exported for builders)
    get_mask_generator, get_apply_masks,
)

# ─────────────────────────────────────────────────────────────────────────
# Module constants (extracted from m09_pretrain.py:78-89)
# ─────────────────────────────────────────────────────────────────────────
CHECKPOINT_PREFIX = "m09_ckpt"
_pcfg = get_pipeline_config()
DECODE_WORKERS = _pcfg["streaming"]["decode_workers_train"]
MAX_STREAM_RETRIES = _pcfg["streaming"]["max_retries"]

# Alias used by producer_thread — matches m09_pretrain.py:89
_create_stream = create_stream


# ═════════════════════════════════════════════════════════════════════════
# CONFIG
# ═════════════════════════════════════════════════════════════════════════

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


# ═════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═════════════════════════════════════════════════════════════════════════

def load_val_subset(val_subset_path: str) -> set:
    """Load val subset clip keys from JSON (generated by m00c_sample_subset.py)."""
    if not val_subset_path:
        return set()
    p = Path(val_subset_path)
    if not p.exists():
        print(f"FATAL: Val subset file not found: {p}")
        sys.exit(1)
    with open(p) as f:
        data = json.load(f)
    keys = set(data["clip_keys"])
    print(f"[VAL] Loaded val subset: {len(keys):,} clips from {p.name}")
    return keys


# ImageNet normalization — MUST match Meta's V-JEPA training pipeline.
# deps/vjepa2/app/vjepa/transforms.py line 110: _tensor_normalize_inplace(buffer, mean, std)
# Without this, the model sees [0,1] range during training but [-2,2.6] during evaluation
# (HF processor normalizes). The mismatch caused -26% Prec@K artifact.
IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(1, 3, 1, 1)
IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(1, 3, 1, 1)


def augment_clip_consistent(video_tensor: torch.Tensor, cfg_aug: dict,
                            crop_size: int) -> torch.Tensor:
    """Video-consistent augmentation matching Meta's V-JEPA pipeline exactly.

    Steps: RandomResizedCrop → HorizontalFlip → ImageNet normalize.
    Matches deps/vjepa2/app/vjepa/transforms.py:VideoTransform.__call__().
    """
    import torchvision.transforms as TT

    T_frames, C, H, W = video_tensor.shape
    scale = cfg_aug["random_resize_scale"]
    ratio = cfg_aug["random_resize_ratio"]

    i, j, h, w = TT.RandomResizedCrop.get_params(
        video_tensor[0], scale=scale, ratio=ratio)

    video = video_tensor.float() / 255.0
    video = video[:, :, i:i+h, j:j+w]
    video = F.interpolate(video, size=(crop_size, crop_size),
                          mode='bilinear', align_corners=False)

    if torch.rand(1).item() < cfg_aug["horizontal_flip"]:
        video = video.flip(-1)

    # ImageNet normalization — matches Meta's training exactly
    video = (video - IMAGENET_MEAN.to(video.device)) / IMAGENET_STD.to(video.device)

    return video  # (T, C, crop_size, crop_size), ImageNet-normalized


def producer_thread(cfg: dict, q: queue.Queue, stop_event: threading.Event,
                    train_keys: set, processed_steps: int):
    """Stream WebDataset, decode videos, augment, enqueue batches (multi-epoch)."""
    from concurrent.futures import ThreadPoolExecutor

    # Prevent ATen thread oversubscription (CLAUDE.md rule #12)
    torch.set_num_threads(1)

    batch_size = cfg["optimization"]["batch_size"]
    num_frames = cfg["data"]["num_frames"]
    crop_size = cfg["data"]["crop_size"]
    local_data = cfg["data"]["local_data"]
    cfg_aug = cfg["augmentation"]
    retries = 0
    epoch = 0

    tmp_dir = tempfile.mkdtemp(prefix="m09_")

    def _decode_batch(pool, pending_bytes, pending_keys):
        """Decode + augment a batch using the shared thread pool."""
        futures = [
            pool.submit(decode_video_bytes, b, tmp_dir, k, num_frames)
            for b, k in zip(pending_bytes, pending_keys)
        ]
        results = [(f.result(), k) for f, k in zip(futures, pending_keys)]

        batch_tensors = [t for t, k in results if t is not None]
        batch_keys = [k for t, k in results if t is not None]

        if batch_tensors:
            augmented = [augment_clip_consistent(vt, cfg_aug, crop_size)
                         for vt in batch_tensors]
            batch = torch.stack(augmented, dim=0).permute(0, 2, 1, 3, 4)
            q.put(("batch", batch, batch_keys[:]))

    try:
        # Single thread pool for entire producer lifetime (avoids thread exhaustion —
        # creating per-batch leaks threads: CPython #98467, ffmpeg spawns 16 internal
        # threads per decoder when thread_count=0)
        with ThreadPoolExecutor(max_workers=DECODE_WORKERS) as pool:
            while not stop_event.is_set():
                try:
                    epoch += 1
                    if epoch > 1:
                        print(f"  Producer: starting epoch {epoch}")
                    pending_bytes, pending_keys = [], []

                    if local_data:
                        # Fast path: parallel TAR readers (8 threads per epoch)
                        clip_q, tar_stop, _reader = iter_clips_parallel(
                            local_data, subset_keys=train_keys or None)
                        while not stop_event.is_set():
                            item = clip_q.get(timeout=120)
                            if item is None:
                                break
                            clip_key, mp4_bytes = item
                            if not mp4_bytes:
                                continue
                            pending_bytes.append(mp4_bytes)
                            pending_keys.append(clip_key)
                            if len(pending_bytes) >= batch_size:
                                _decode_batch(pool, pending_bytes, pending_keys)
                                pending_bytes, pending_keys = [], []
                        tar_stop.set()
                    else:
                        # Fallback: sequential HF streaming
                        ds = _create_stream(0, local_data=local_data)
                        for example in ds:
                            if stop_event.is_set():
                                break
                            clip_key = get_clip_key(example)
                            if train_keys and clip_key not in train_keys:
                                continue
                            mp4_data = example.get("mp4", b"")
                            mp4_bytes = mp4_data["bytes"] if isinstance(mp4_data, dict) else mp4_data
                            if not mp4_bytes:
                                continue
                            pending_bytes.append(mp4_bytes)
                            pending_keys.append(clip_key)
                            if len(pending_bytes) >= batch_size:
                                _decode_batch(pool, pending_bytes, pending_keys)
                                pending_bytes, pending_keys = [], []

                    # Handle final partial batch
                    if pending_bytes and not stop_event.is_set():
                        _decode_batch(pool, pending_bytes, pending_keys)

                    # Loop to next epoch (don't break — training needs multiple passes)

                except (ConnectionError, TimeoutError, OSError) as e:
                    retries += 1
                    if retries > MAX_STREAM_RETRIES:
                        print(f"  FATAL: stream failed after {MAX_STREAM_RETRIES} retries: {e}")
                        break
                    wait = min(2 ** retries, 60)
                    print(f"  Stream error ({e}), retry {retries}/{MAX_STREAM_RETRIES} in {wait}s")
                    time.sleep(wait)
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)
        q.put(("error" if retries > MAX_STREAM_RETRIES else "done", None, None))


# ═════════════════════════════════════════════════════════════════════════
# MASKING (Q4: Use _MaskGenerator directly, not MaskCollator)
# ═════════════════════════════════════════════════════════════════════════

def build_mask_generators(cfg: dict) -> list:
    """Build one _MaskGenerator per mask config."""
    _MaskGenerator = get_mask_generator()

    data_cfg = cfg["data"]
    model_cfg = cfg["model"]  # crop_size/patch_size/tubelet_size live under model: per configs/model/vjepa2_*.yaml (#51)
    generators = []
    for m_cfg in cfg["mask"]:
        mg = _MaskGenerator(
            crop_size=(model_cfg["crop_size"], model_cfg["crop_size"]),
            num_frames=data_cfg["num_frames"],
            spatial_patch_size=(model_cfg["patch_size"], model_cfg["patch_size"]),
            temporal_patch_size=model_cfg["tubelet_size"],
            spatial_pred_mask_scale=m_cfg["spatial_scale"],
            temporal_pred_mask_scale=m_cfg["temporal_scale"],
            aspect_ratio=m_cfg["aspect_ratio"],
            npred=m_cfg["num_blocks"],
        )
        generators.append(mg)
    return generators


# ═════════════════════════════════════════════════════════════════════════
# LOSS (L1 latent prediction + drift control)
# ═════════════════════════════════════════════════════════════════════════

def compute_jepa_loss(pred_features: list, pred_context: list,
                      teacher_output: torch.Tensor,
                      masks_pred: list, masks_enc: list,
                      loss_exp: float, predict_all: bool,
                      lambda_context: float = 0.5) -> tuple:
    """V-JEPA 2.1 dense loss: masked tokens + context tokens.

    When predict_all=True (V-JEPA 2.1), computes loss on ALL tokens:
    - Masked loss: predictor output vs teacher at masked positions
    - Context loss: predictor context output vs teacher at visible positions
    - Total = masked_loss + lambda_context * context_loss

    Returns (total_loss, loss_masked, loss_context).
    """
    apply_masks = get_apply_masks()

    # Masked token loss
    loss_masked = torch.tensor(0.0, device=teacher_output.device)
    n = 0
    for pred_i, mask_i in zip(pred_features, masks_pred):
        h_masked = apply_masks(teacher_output, [mask_i])
        loss_masked += torch.mean(torch.abs(pred_i - h_masked) ** loss_exp) / loss_exp
        n += 1
    loss_masked = loss_masked / max(n, 1)

    # Context token loss (V-JEPA 2.1 dense loss — doubles training signal)
    loss_context = torch.tensor(0.0, device=teacher_output.device)
    if predict_all and pred_context:
        n_ctx = 0
        for ctx_i, mask_enc_i in zip(pred_context, masks_enc):
            if ctx_i is None:
                continue
            h_context = apply_masks(teacher_output, [mask_enc_i])
            loss_context += torch.mean(torch.abs(ctx_i - h_context) ** loss_exp) / loss_exp
            n_ctx += 1
        loss_context = loss_context / max(n_ctx, 1)

    total = loss_masked + lambda_context * loss_context
    return total, loss_masked, loss_context


def compute_drift_loss(student: torch.nn.Module, init_params: dict,
                       lambda_reg: float) -> torch.Tensor:
    """L2 drift control: lambda * ||theta - theta_0||^2 (Sec 10.4)."""
    device = next(student.parameters()).device
    drift = torch.tensor(0.0, device=device)
    for name, param in student.named_parameters():
        if name in init_params:
            drift += torch.sum((param - init_params[name].to(device)) ** 2)
    return lambda_reg * drift


def _train_step_grad_accum(student, teacher, predictor, batch_clips,
                           all_masks_enc, all_masks_pred,
                           cfg, dtype, mp_cfg, scaler, sizer, loss_exp,
                           init_params=None, drift_cfg=None):
    """Forward+backward with adaptive micro-batch sizing + gradient accumulation (#48).

    Splits the macro batch into micro-batches of `sizer.size`, runs forward+backward
    per micro, scales each micro's loss by (micro_size / macro_size) so accumulated
    gradients are mathematically identical to a single full-batch step. The optimizer
    step + zero_grad happen ONCE per macro in the caller — preserving effective batch
    size, optimizer dynamics (Adam momentum, weight-decay scheduling, LR scaling),
    and convergence behavior. Only the GPU memory footprint shrinks.

    Drift loss (parameter regularizer, no batch dim) is added once after the micro
    loop with full weight — equivalent to a single-batch step.

    Returns (jepa_val, masked_val, context_val, drift_val) — running totals
    weighted to match macro-batch mean (interpretable for logging).

    On OOM: cuda_cleanup + sizer.on_oom + raises — caller calls optimizer.zero_grad()
    to discard partial gradients and retries on the next producer batch.
    """
    embed_dim = cfg["model"]["embed_dim"]
    n_levels = cfg["model"]["n_output_distillation"]
    predict_all = cfg["model"]["predict_all"]
    macro_bs = batch_clips.shape[0]

    j_val, m_val, c_val = 0.0, 0.0, 0.0
    i = 0
    while i < macro_bs:
        end = min(i + sizer.size, macro_bs)
        micro_bs = end - i
        weight = micro_bs / macro_bs

        bc = batch_clips[i:end]
        m_enc_list = [m[i:end] for m in all_masks_enc]
        m_pred_list = [m[i:end] for m in all_masks_pred]

        try:
            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                with torch.no_grad():
                    h = teacher(bc)
                    if h.size(-1) == n_levels * embed_dim:
                        chunks = [F.layer_norm(h[:, :, lvl * embed_dim:(lvl + 1) * embed_dim],
                                               (embed_dim,))
                                  for lvl in range(n_levels)]
                        h = torch.cat(chunks, dim=2)
                    else:
                        h = F.layer_norm(h, (h.size(-1),))
                pf, pc = [], []
                for k, (me, mp) in enumerate(zip(m_enc_list, m_pred_list)):
                    z = student(bc, masks=[me])
                    out = predictor(z, [me], [mp], mask_index=k)
                    if isinstance(out, tuple) and len(out) == 2:
                        pf.append(out[0]); pc.append(out[1])
                    else:
                        pf.append(out)
                jl, lm, lc = compute_jepa_loss(pf, pc, h, m_pred_list, m_enc_list,
                                                loss_exp, predict_all, lambda_context=0.5)
            scaler.scale(jl * weight).backward()
        except torch.cuda.OutOfMemoryError:
            cuda_cleanup()
            sizer.on_oom()
            raise

        j_val += jl.item() * weight
        m_val += lm.item() * weight
        c_val += lc.item() * weight
        i = end

    drift_val = 0.0
    if init_params is not None and drift_cfg is not None \
            and drift_cfg.get("enabled") and drift_cfg.get("lambda_reg", 0) > 0:
        drift_loss = compute_drift_loss(student, init_params, drift_cfg["lambda_reg"])
        scaler.scale(drift_loss).backward()
        drift_val = drift_loss.item()

    sizer.after_batch_success()
    return j_val, m_val, c_val, drift_val


# ═════════════════════════════════════════════════════════════════════════
# EMA TEACHER UPDATE
# ═════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def update_teacher_ema(student: torch.nn.Module, teacher: torch.nn.Module,
                       momentum: float):
    """EMA update: theta_bar <- tau * theta_bar + (1-tau) * theta.

    Uses name-based matching so ExPLoRA LoRA params (which only exist in student,
    not teacher) are safely skipped.
    """
    student_dict = dict(student.named_parameters())
    for name, param_t in teacher.named_parameters():
        if name in student_dict:
            param_t.mul_(momentum).add_(student_dict[name].data, alpha=1.0 - momentum)


# ═════════════════════════════════════════════════════════════════════════
# OPTIMIZER & SCHEDULER
# ═════════════════════════════════════════════════════════════════════════

def build_optimizer(student, predictor, cfg_opt: dict):
    """Build AdamW optimizer. Reads `use_8bit_optim` flag (#56) — when True, uses
    bitsandbytes `AdamW8bit` for 4× optimizer-state memory reduction (m1+m2 stored
    as 8-bit block-wise quantized values instead of fp32). <1% accuracy loss per
    Dettmers et al. 2022 ("8-bit Optimizers via Block-wise Quantization",
    arXiv:2110.02861). Standard in HF Trainer (`optim="adamw_bnb_8bit"`) and FAIR
    fairscale for fine-tuning 2B+ models on consumer GPUs.
    """
    base_lr = cfg_opt["lr"]
    pred_lr = base_lr * cfg_opt["pred_lr_multiplier"]
    wd = cfg_opt["weight_decay"]
    use_8bit = cfg_opt["use_8bit_optim"]

    def split_params(module, lr):
        decay, no_decay = [], []
        for name, p in module.named_parameters():
            if not p.requires_grad:
                continue
            if "bias" in name or "norm" in name or "ln" in name:
                no_decay.append(p)
            else:
                decay.append(p)
        return [
            {"params": decay, "lr": lr, "weight_decay": wd},
            {"params": no_decay, "lr": lr, "weight_decay": 0.0},
        ]

    param_groups = split_params(student, base_lr) + split_params(predictor, pred_lr)

    if use_8bit:
        import bitsandbytes as bnb
        # Paged variant (#58) — auto CPU paging of optimizer state on GPU pressure.
        # ONLY read `paged_optim` inside this branch so non-8bit configs (m09a/m09b,
        # m09c POC/FULL) never require the key in their yaml. HF QLoRA standard for
        # fine-tuning 7-65B models on 24-48 GB consumer GPUs.
        paged_optim = cfg_opt["paged_optim"]
        if paged_optim:
            opt = bnb.optim.PagedAdamW8bit(param_groups,
                                             betas=tuple(cfg_opt["betas"]),
                                             eps=cfg_opt["eps"])
            optim_name = "PagedAdamW8bit (bitsandbytes, unified-memory CPU paging)"
        else:
            opt = bnb.optim.AdamW8bit(param_groups,
                                       betas=tuple(cfg_opt["betas"]),
                                       eps=cfg_opt["eps"])
            optim_name = "AdamW8bit (bitsandbytes)"
        n_trainable = sum(len(g["params"]) for g in param_groups)
        print(f"  Optimizer: {optim_name} — {n_trainable} param groups, "
              f"8-bit block-wise quantized m1/m2 (4× memory reduction)")
        return opt
    return torch.optim.AdamW(param_groups, betas=tuple(cfg_opt["betas"]),
                              eps=cfg_opt["eps"])


def enable_gradient_checkpointing(model):
    """Wrap each transformer block's forward in `torch.utils.checkpoint.checkpoint`
    for activation-memory savings (#56). Activations recomputed during backward
    instead of stored → ~2-4× reduction in activation memory at cost of ~25-30%
    throughput (one extra forward pass per block during backward).

    Uses `use_reentrant=False` (modern PyTorch API, required for torch.compile
    compatibility + proper handling of keyword args — V-JEPA blocks accept
    `mask`, `T`, `H_patches`, `W_patches`, `return_attn`, `mode` as kwargs).

    Works for BOTH trainable and frozen blocks — frozen blocks still consume
    activation memory during forward (autograd needs them to backprop gradient
    to earlier trainable blocks), so checkpointing helps regardless of
    `requires_grad`. Gold-standard pattern used by HF Transformers
    `gradient_checkpointing_enable()` and FAIR vissl's checkpoint_wrapper.

    Must be called AFTER model.train() is set and BEFORE build_optimizer —
    safe to call once per stage (idempotent via `_gradient_checkpointing` attr).
    """
    if getattr(model, "_gradient_checkpointing", False):
        return  # idempotent — already wrapped
    if not hasattr(model, "blocks"):
        raise ValueError(f"enable_gradient_checkpointing: model {type(model).__name__} "
                         f"has no .blocks attribute (expected nn.ModuleList)")

    import torch.utils.checkpoint as ckpt

    def make_ckpt_wrapper(original_forward):
        def checkpointed_forward(*args, **kwargs):
            return ckpt.checkpoint(original_forward, *args,
                                   use_reentrant=False, **kwargs)
        return checkpointed_forward

    for block in model.blocks:
        block.forward = make_ckpt_wrapper(block.forward)

    model._gradient_checkpointing = True
    print(f"  Gradient checkpointing enabled on {len(model.blocks)} blocks "
          f"(~2-4× activation memory reduction, ~25% throughput cost)")


def build_scheduler(optimizer, cfg_opt: dict, total_steps: int):
    # Cap warmup to 10% of total steps (avoids never leaving warmup on short runs)
    warmup_cap_pct = cfg_opt["warmup_cap_pct"]
    warmup_steps = min(cfg_opt["warmup_steps"], max(1, total_steps * warmup_cap_pct // 100))
    min_lr = cfg_opt["min_lr"]
    base_lr = cfg_opt["lr"]

    def lr_lambda(step):
        if step < warmup_steps:
            return step / max(warmup_steps, 1)
        progress = (step - warmup_steps) / max(total_steps - warmup_steps, 1)
        return max(min_lr / base_lr, 0.5 * (1 + np.cos(np.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


def update_weight_decay(optimizer, cfg_opt: dict, step: int, total_steps: int):
    """Cosine weight decay schedule (matches Meta's CosineWDSchedule).

    Ramps WD from weight_decay to final_weight_decay over training.
    If both are equal (default: 0.04), this is a no-op.
    """
    initial_wd = cfg_opt["weight_decay"]
    final_wd = cfg_opt["final_weight_decay"]
    if initial_wd == final_wd:
        return  # no-op: fixed WD
    progress = step / max(total_steps, 1)
    new_wd = final_wd + 0.5 * (initial_wd - final_wd) * (1 + np.cos(np.pi * progress))
    for group in optimizer.param_groups:
        if group.get("weight_decay", 0) > 0:  # don't touch no_decay groups
            group["weight_decay"] = new_wd


# ═════════════════════════════════════════════════════════════════════════
# VALIDATION (JEPA L1 loss on held-out val clips)
# ═════════════════════════════════════════════════════════════════════════

def run_validation(student, teacher, predictor, mask_generators,
                   val_batches: list, cfg: dict, device: torch.device,
                   step: int) -> float:
    """Compute JEPA L1 loss on val clips. Same as training loss, different data.

    Returns mean val loss (scalar).
    """
    student.eval()
    predictor.eval()

    mp_cfg = cfg["mixed_precision"]
    dtype = getattr(torch, mp_cfg["dtype"])
    loss_exp = cfg["optimization"]["loss_exp"]
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch_clips in val_batches:
            batch_clips = batch_clips.to(device)
            actual_bs = batch_clips.shape[0]

            # Generate masks (same as training)
            all_masks_enc, all_masks_pred = [], []
            for mg in mask_generators:
                m_enc, m_pred = mg(actual_bs)
                all_masks_enc.append(m_enc.to(device))
                all_masks_pred.append(m_pred.to(device))

            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                # Teacher: all tokens + per-chunk LayerNorm (deep supervision)
                embed_dim_val = cfg["model"]["embed_dim"]
                n_levels_val = cfg["model"]["n_output_distillation"]
                h = teacher(batch_clips)
                if h.size(-1) == n_levels_val * embed_dim_val:
                    chunks = []
                    for lvl in range(n_levels_val):
                        chunk = h[:, :, lvl * embed_dim_val : (lvl + 1) * embed_dim_val]
                        chunks.append(F.layer_norm(chunk, (embed_dim_val,)))
                    h = torch.cat(chunks, dim=2)
                else:
                    h = F.layer_norm(h, (h.size(-1),))

                # Student + Predictor per mask generator
                predict_all_val = cfg["model"]["predict_all"]
                pred_features = []
                pred_context_val = []
                for i, (m_enc, m_pred) in enumerate(zip(all_masks_enc, all_masks_pred)):
                    z = student(batch_clips, masks=[m_enc])
                    outputs = predictor(z, [m_enc], [m_pred], mask_index=i)
                    if isinstance(outputs, tuple) and len(outputs) == 2:
                        pred_features.append(outputs[0])
                        pred_context_val.append(outputs[1])
                    else:
                        pred_features.append(outputs)

                # Dense loss (same as training, no drift control)
                jepa_loss, _, _ = compute_jepa_loss(
                    pred_features, pred_context_val, h,
                    all_masks_pred, all_masks_enc,
                    loss_exp, predict_all_val, lambda_context=0.5)

            total_loss += jepa_loss.item()
            n_batches += 1

    val_loss = total_loss / max(n_batches, 1)
    print(f"  Step {step} | Val JEPA loss: {val_loss:.4f} ({len(val_batches)} batches)")

    student.train()
    predictor.train()
    return val_loss


# ═════════════════════════════════════════════════════════════════════════
# CHECKPOINT
# ═════════════════════════════════════════════════════════════════════════

def save_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler,
                              step: int, best_metric: float,
                              full: bool = True):
    """Save checkpoint.

    iter11 disk-budget fix (2026-04-24, after POC v3 disk-full crash at step 6):
    teacher + predictor were previously ALWAYS included. For a ViT-G 2B model:
      student    ≈ 4 GB (bf16) or 8 GB (fp32)
      teacher    ≈ 4 GB / 8 GB — deepcopy of student, only needed for EMA-resume
      predictor  ≈ 240 MB
      optimizer  ≈ 16 GB (AdamW, 2 fp32 moments × 2B params)
    With `full=True` → ~24 GB per ckpt. POC writes 5 live ckpts → 120 GB → disk-full.

    New semantics:
      full=True  → resume-capable: student + teacher + predictor + optimizer + scheduler + scaler
                   (~20-24 GB on ViT-G). Use for m09*_ckpt_latest.pt (one file, resume anchor).
      full=False → SELECTION-ONLY: student ONLY (~4 GB). Use for step*.pt, best.pt,
                   best_prec.pt — they're read only to pick the "best" student and export it;
                   teacher/predictor are rebuilt on resume via student EMA init anyway.
    POC footprint after fix: 4+4 (2 steps @ keep_n=2) + 20 (latest) + 4 (best) + 4 (best_prec)
    = 36 GB peak (vs 120 GB before).
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(".tmp")
    ckpt = {
        "student": student.state_dict(),
        "step": step,
        "best_metric": best_metric,
        "is_full": full,                      # marker for load_training_checkpoint fallback
    }
    if full:
        ckpt["teacher"] = teacher.state_dict()
        ckpt["predictor"] = predictor.state_dict()
        ckpt["optimizer"] = optimizer.state_dict()
        ckpt["scheduler"] = scheduler.state_dict()
        ckpt["scaler"] = scaler.state_dict() if scaler else None
    torch.save(ckpt, tmp_path)
    os.replace(tmp_path, path)


def cleanup_old_checkpoints(output_dir: Path, prefix: str, keep_n: int = 2,
                             cache_policy: str = "1"):
    """Delete oldest {prefix}_step*.pt files, keeping only the last keep_n.

    iter11 META-fix: gated through cache_policy. Default=1/keep short-circuits all
    deletes (preserves disk vs. resume-safety tradeoff for the user to choose).
    Caller must pass cache_policy=args.cache_policy to honor the .sh prompt.

    `prefix` MUST match the caller module's CHECKPOINT_PREFIX (e.g. "m09b_ckpt")
    — previously this was hardcoded to the utils-module CHECKPOINT_PREFIX
    ("m09_ckpt"), causing a silent zero-match glob for m09b (writes "m09b_ckpt_*")
    and m09c (writes "m09c_ckpt_*"), which piled up ckpts until disk-full.
    """
    from utils.cache_policy import guarded_delete
    pattern = str(output_dir / f"{prefix}_step*.pt")
    step_files = sorted(glob.glob(pattern),
                        key=lambda f: os.path.getmtime(f))
    if len(step_files) > keep_n:
        for old_file in step_files[:-keep_n]:
            guarded_delete(old_file, cache_policy, label="m09 step checkpoint")


def cleanup_stage_checkpoints(output_dir: Path, prefix: str, keep_n: int = 1,
                               cache_policy: str = "1"):
    """Delete oldest `{prefix}_stage*.pt` files, keeping only the last `keep_n`.

    Mirror of `cleanup_old_checkpoints` but for **stage-suffixed** saves
    (m09c surgery writes stage0 / stage1 / stage2 — not step-N). Keeps disk
    footprint at `keep_n × ~15 GB` instead of cumulative `3 × ~15 GB`.

    Usage in m09c:
      - Mid-training (per-stage save): `keep_n=1` → one resume anchor on disk.
      - Post-export (after `export_student_for_eval`): `keep_n=0` → student_encoder.pt
        is the only artifact downstream needs, stage rollback points are disposable.

    The glob is sorted by mtime so the N most-recent writes survive regardless of
    stage ordering (important if a resume re-writes stage2 with a newer timestamp
    than stage0/1 — we keep the "newest save", not the "highest stage index").
    """
    pattern = str(output_dir / f"{prefix}_stage*.pt")
    stage_files = sorted(glob.glob(pattern),
                         key=lambda f: os.path.getmtime(f))
    if len(stage_files) > keep_n:
        target = stage_files[:-keep_n] if keep_n > 0 else stage_files
        # iter11 META-fix: gate destructive stage-ckpt cleanup through cache_policy.
        # Default=1/keep is safe; pass cache_policy=args.cache_policy from orchestrator.
        from utils.cache_policy import guarded_delete
        for old_file in target:
            guarded_delete(old_file, cache_policy,
                           label="m09c stage checkpoint")


def load_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler) -> tuple:
    ckpt = torch.load(path, map_location="cuda", weights_only=False)
    student.load_state_dict(ckpt["student"])
    if "teacher" in ckpt:
        teacher.load_state_dict(ckpt["teacher"])
    if "predictor" in ckpt:
        predictor.load_state_dict(ckpt["predictor"])
    if "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    if "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    if scaler and ckpt.get("scaler"):
        scaler.load_state_dict(ckpt["scaler"])
    return ckpt["step"], ckpt.get("best_metric", float("inf"))


def export_student_for_eval(student, path: Path, explora_enabled: bool = False):
    """Export student encoder weights + metadata for m05/m06 re-evaluation."""
    from utils.config import VJEPA_MODEL_ID
    path.parent.mkdir(parents=True, exist_ok=True)
    # ExPLoRA: merge LoRA weights into base model before saving
    export_model = student
    if explora_enabled and hasattr(student, "merge_and_unload"):
        print("  Merging LoRA weights into base model for export...")
        export_model = student.merge_and_unload()
    torch.save({
        "student_state_dict": export_model.state_dict(),
        "model_id": VJEPA_MODEL_ID,
        "type": "vjepa2_adapted",
    }, path)
    print(f"Exported student encoder: {path}")


# ═════════════════════════════════════════════════════════════════════════
# SURGERY HELPERS (Ch11 — progressive prefix unfreezing + factor datasets)
# ═════════════════════════════════════════════════════════════════════════

def set_trainable_prefix(student, n_layers: int):
    """Freeze all blocks, then unfreeze blocks [0, n_layers). Rebuild optimizer after calling."""
    for param in student.parameters():
        param.requires_grad = False
    for i in range(min(n_layers, len(student.blocks))):
        for param in student.blocks[i].parameters():
            param.requires_grad = True
    for name, param in student.named_parameters():
        if "norm" in name or "ln" in name:
            param.requires_grad = True
    trainable = sum(p.numel() for p in student.parameters() if p.requires_grad)
    total = sum(p.numel() for p in student.parameters())
    print(f"  Trainable prefix: {n_layers}/{len(student.blocks)} blocks "
          f"({trainable:,}/{total:,} = {100*trainable/total:.1f}%)")


def create_train_val_split(clip_keys, split_ratio: float, seed: int,
                           max_val_clips: int = 1000):
    """Deterministic train/val split via seeded shuffle. Reproducible across runs
    with same (keys, split_ratio, seed, max_val_clips). Used by m09c to carve a
    held-out val-set from the factor manifest so the same set powers mid-training
    probe + downstream Step F decision gate — eliminates the 2026-04-19 test-leakage flaw.

    val_size = min(max_val_clips, int(n * (1 - split_ratio))). Cap prevents FULL
    (115K clips × 10% = 11500) from burning GPU on an over-sized val-set when 1000
    clips already give tight BCa CIs. POC (1000 × 10% = 100) is below cap → 100 val.

    split_ratio=1.0 returns (all_keys, []) — SANITY uses this (N=20 too small to split).
    """
    if split_ratio >= 1.0:
        return list(clip_keys), []
    rng = random.Random(seed)
    shuffled = list(clip_keys)
    rng.shuffle(shuffled)
    n_total = len(shuffled)
    # Avoid `n_total * (1 - split_ratio)` — IEEE 754 rounds 1-0.9 = 0.0999... → off-by-one.
    # Compute n_train first (exact for round multiples), derive n_val from it, then cap.
    n_train = int(n_total * split_ratio)
    n_val = min(max_val_clips, n_total - n_train)
    n_train = n_total - n_val   # re-derive so cap actually increases n_train on FULL
    return shuffled[:n_train], shuffled[n_train:]


def build_factor_index(manifest: dict, dl_dir: Path, da_dir: Path, di_dir: Path) -> dict:
    """Build clip_key → {D_L: path, D_A: path, D_I: [paths]} from m11 manifest."""
    index = {}
    for clip_key, info in manifest.items():
        safe_key = clip_key.replace("/", "__")
        entry = {}
        if info["has_D_L"]:
            p = dl_dir / f"{safe_key}.npy"
            if p.exists():
                entry["D_L"] = p
        if info["has_D_A"]:
            p = da_dir / f"{safe_key}.npy"
            if p.exists():
                entry["D_A"] = p
        if info.get("has_D_I") and info.get("n_interaction_tubes", 0) > 0:
            tubes = sorted(di_dir.glob(f"{safe_key}_tube*.npy"))
            if tubes:
                entry["D_I"] = tubes
        if entry:
            index[clip_key] = entry
    print(f"  Factor index: {len(index)} clips "
          f"(D_L={sum(1 for e in index.values() if 'D_L' in e)}, "
          f"D_A={sum(1 for e in index.values() if 'D_A' in e)}, "
          f"D_I={sum(1 for e in index.values() if 'D_I' in e)})")
    return index


class FactorSampler:
    """Sample factor clips according to per-stage mode mixture weights."""

    def __init__(self, factor_index: dict, mode_mixture: dict):
        factor_map = {"L": "D_L", "A": "D_A", "I": "D_I"}
        self.clips_by_factor = {}
        for fk in ["D_L", "D_A", "D_I"]:
            self.clips_by_factor[fk] = [
                (key, entry[fk])
                for key, entry in factor_index.items()
                if fk in entry
            ]
        self.factors = []
        self.weights = []
        for mode_key, weight in mode_mixture.items():
            if weight <= 0:
                continue
            fk = factor_map[mode_key]
            if not self.clips_by_factor[fk]:
                counts = {k: len(v) for k, v in self.clips_by_factor.items()}
                raise ValueError(
                    f"FactorSampler: mode_mixture requests {mode_key}={weight} "
                    f"but clips_by_factor[{fk}] is empty (counts={counts}). "
                    f"Silent renormalization banned per CLAUDE.md §5. Fix: regenerate "
                    f"{fk} upstream OR set {mode_key}=0.0 in yaml mode_mixture."
                )
            self.factors.append(fk)
            self.weights.append(weight)
        if not self.factors:
            raise ValueError(
                f"FactorSampler: no positive weights in mode_mixture={mode_mixture}"
            )
        total_w = sum(self.weights)
        self.weights = [w / total_w for w in self.weights]
        requested = {k: v for k, v in mode_mixture.items() if v > 0}
        actual = dict(zip(self.factors, self.weights))
        print(
            f"  FactorSampler: REQUESTED={requested} → "
            f"ACTUAL={{{', '.join(f'{f}={w:.0%}' for f, w in actual.items())}}}"
        )

    def sample(self) -> tuple:
        """Returns (factor_type, clip_key, path_or_paths)."""
        factor = np.random.choice(self.factors, p=self.weights)
        clips = self.clips_by_factor[factor]
        idx = np.random.randint(len(clips))
        clip_key, path = clips[idx]
        if isinstance(path, list):
            path = path[np.random.randint(len(path))]
        return factor, clip_key, path


# ═════════════════════════════════════════════════════════════════════════
# STREAMING FACTOR GENERATION — on-demand D_L / D_A from (raw_mp4, mask) pairs
# ═════════════════════════════════════════════════════════════════════════
# Purpose: eliminate m11's ~340 GB disk write at 10K / ~4 TB at 115K by
# generating D_L / D_A inside DataLoader workers. Keeps m10 masks + raw MP4s
# on disk; factor arrays materialize only in worker RAM, feed directly to
# student forward. Unlocks full 10K → 50K → 115K ladder on a single 500 GB
# instance (vs 500 GB → 3 TB → 5 TB rent ladder).
#
# Contract (technique-agnostic):
#   - StreamingFactorDataset takes (mp4_index, mask_index, factor_cfg,
#     mode_mixture, ...) as explicit params. NO argparse/technique branching.
#   - D_L / D_A stream via utils.factor_streaming.stream_factor; D_I stays
#     on legacy disk path (Stage 3 retired in iter9's 2-stage recipe).
#   - Worker init forces torch.set_num_threads(1) + PyAV thread_count=1 (R2
#     in plan_code_dev.md risk register).
#
# Bitwise parity with legacy .npy: guaranteed by (a) importing m11's
# make_layout_only/make_agent_only directly, (b) mirroring m11:652-664 mask
# alignment, (c) sharing tensor_from_factor_array normalization with
# load_factor_clip.

def build_streaming_indices(manifest_path: Path, masks_dir: Path, local_data: str) -> tuple:
    """Map clip_keys → (TAR path, base name) and mask .npz paths.

    One-shot scan of the local TAR pool in the main process. Called once at
    stage setup, passed to DataLoader workers via dataset __init__ — workers
    re-open TARs locally (fork-safe), never sharing iter_clips_parallel's
    threads.

    Args:
        manifest_path: path to m11 factor_manifest.json
        masks_dir: directory holding m10 .npz mask files
        local_data: path to local_data dir with *.tar shards

    Returns:
        (mp4_index, mask_index, factor_manifest)
            mp4_index: {clip_key: (tar_path: str, base_name: str)}
            mask_index: {clip_key: npz_path: Path}
            factor_manifest: loaded m11 manifest dict (for has_D_L/has_D_A gating)
    """
    import tarfile
    factor_manifest = json.loads(Path(manifest_path).read_text())
    manifest_keys = set(factor_manifest.keys())

    tar_files = sorted(Path(local_data).glob("*.tar"))
    if not tar_files:
        raise FileNotFoundError(
            f"build_streaming_indices: no *.tar files in {local_data}. "
            f"Did you run ./git_pull.sh to fetch local_data?")

    mp4_index = {}
    from utils.data_download import _get_clip_key
    for tar_path in tar_files:
        with tarfile.open(tar_path, "r") as tar:
            entries = {}
            for member in tar.getmembers():
                base = member.name.rsplit(".", 1)[0]
                ext = member.name.rsplit(".", 1)[-1] if "." in member.name else ""
                entries.setdefault(base, {})[ext] = member
            for base, parts in entries.items():
                if "json" not in parts or "mp4" not in parts:
                    continue
                json_bytes = tar.extractfile(parts["json"]).read()
                clip_key = _get_clip_key(json_bytes)
                if clip_key in manifest_keys and clip_key not in mp4_index:
                    mp4_index[clip_key] = (str(tar_path), base)

    mask_index = {}
    masks_dir = Path(masks_dir)
    for clip_key in manifest_keys:
        safe_key = clip_key.replace("/", "__")
        npz_path = masks_dir / f"{safe_key}.npz"
        if npz_path.exists():
            mask_index[clip_key] = npz_path

    indexed = set(mp4_index.keys()) & set(mask_index.keys())
    dropped = manifest_keys - indexed
    if dropped:
        print(f"  build_streaming_indices: {len(dropped)} manifest clips missing "
              f"MP4 or mask — excluded. Sample: {list(dropped)[:3]}")
    print(f"  build_streaming_indices: {len(indexed)} clips ready "
          f"({len(mp4_index)} mp4, {len(mask_index)} masks, {len(tar_files)} TARs scanned)")
    return mp4_index, mask_index, factor_manifest


def _streaming_worker_init(worker_id: int) -> None:
    """DataLoader worker_init_fn — single-threaded CPU + seeded RNG.

    CRITICAL (risk R2): without thread_count=1 on PyAV codecs, each worker
    spawns ffmpeg threads → host OOM at num_workers=16. See src/CLAUDE.md
    'Threading' rule.
    """
    info = torch.utils.data.get_worker_info()
    dataset = info.dataset
    seed = ((dataset.base_seed * 1_000_003) ^ (worker_id * 2_718_281)) & 0xFFFFFFFF
    np.random.seed(seed)
    random.seed(seed)
    torch.manual_seed(seed)
    torch.set_num_threads(1)
    try:
        import av
        av.logging.set_level(av.logging.ERROR)
    except ImportError:
        print(f"  worker {worker_id}: PyAV not importable — thread_count not capped")


class StreamingFactorDataset(torch.utils.data.IterableDataset):
    """On-demand D_L / D_A / D_I factor generator for DataLoader.

    Replaces synchronous FactorSampler.sample() + load_factor_clip() with a
    DataLoader-driven pipeline. Each worker owns a shard of clip_keys, samples
    (factor_type, clip_key) per mode_mixture weights, decodes MP4 + mask from
    disk, runs stream_factor() (D_L/D_A) or stream_interaction_tubes() (D_I)
    → normalized tensor.

    Yields dicts with keys {"tensor", "factor_type", "clip_key"} — default
    PyTorch collate stacks tensors, lists strings.

    D_I streaming (iter10 2026-04-22): tubes generated on-demand from
    (mp4_bytes, mask.npz), no disk reads. `di_legacy_index` param retained
    for backward-compat but unused when `interaction_cfg` is passed.
    """

    def __init__(
        self,
        mp4_index: dict,
        mask_index: dict,
        factor_manifest: dict,
        factor_cfg: dict,
        mode_mixture: dict,
        num_frames: int,
        crop_size: int,
        di_legacy_index: dict = None,
        base_seed: int = 42,
        steps_per_epoch: int = None,
        interaction_cfg: dict = None,
    ):
        super().__init__()
        self.mp4_index = mp4_index
        self.mask_index = mask_index
        self.factor_cfg = factor_cfg
        self.num_frames = num_frames
        self.crop_size = crop_size
        self.di_legacy_index = di_legacy_index or {}
        self.interaction_cfg = interaction_cfg
        self.base_seed = base_seed
        self.steps_per_epoch = steps_per_epoch

        factor_map = {"L": "D_L", "A": "D_A", "I": "D_I"}
        indexed_keys = set(mp4_index.keys()) & set(mask_index.keys())
        self.clips_by_factor = {"D_L": [], "D_A": [], "D_I": []}
        for clip_key in indexed_keys:
            info = factor_manifest.get(clip_key, {})
            if info.get("has_D_L"):
                self.clips_by_factor["D_L"].append(clip_key)
            if info.get("has_D_A"):
                self.clips_by_factor["D_A"].append(clip_key)
            # iter10: D_I streaming — manifest's has_D_I (populated from m10
            # mined interactions count) replaces legacy .npy disk presence.
            if info.get("has_D_I"):
                self.clips_by_factor["D_I"].append(clip_key)
        # Back-compat: if legacy disk tubes were provided (pre-iter10) and
        # manifest lacks has_D_I, still populate from legacy index.
        if not self.clips_by_factor["D_I"] and self.di_legacy_index:
            for clip_key, tubes in self.di_legacy_index.items():
                if tubes:
                    self.clips_by_factor["D_I"].append(clip_key)

        self.factors = []
        self.weights = []
        for mode_key, weight in mode_mixture.items():
            if weight <= 0:
                continue
            fk = factor_map[mode_key]
            if not self.clips_by_factor[fk]:
                counts = {k: len(v) for k, v in self.clips_by_factor.items()}
                raise ValueError(
                    f"StreamingFactorDataset: mode_mixture requests {mode_key}={weight} "
                    f"but clips_by_factor[{fk}] is empty (counts={counts}). Silent "
                    f"renormalization would run a different distribution than yaml — "
                    f"failing loud per CLAUDE.md §5. Fix: upstream (e.g., re-run m10 "
                    f"--interactions-only to populate n_interactions for D_I) OR set "
                    f"{mode_key}=0.0 in yaml mode_mixture."
                )
            self.factors.append(fk)
            self.weights.append(weight)
        if not self.factors:
            raise ValueError(
                f"StreamingFactorDataset: no positive weights in mode_mixture={mode_mixture}"
            )
        total_w = sum(self.weights)
        self.weights = [w / total_w for w in self.weights]
        requested = {k: v for k, v in mode_mixture.items() if v > 0}
        actual = dict(zip(self.factors, self.weights))
        print(
            f"  StreamingFactorDataset: REQUESTED={requested} → "
            f"ACTUAL={{{', '.join(f'{f}={w:.0%}' for f, w in actual.items())}}} "
            f"(indexed={len(indexed_keys)} clips)"
        )

    def __iter__(self):
        from utils.factor_streaming import (
            stream_factor, stream_interaction_tubes, tensor_from_factor_array,
        )
        import tarfile

        info = torch.utils.data.get_worker_info()
        if info is None:
            worker_id, num_workers = 0, 1
        else:
            worker_id, num_workers = info.id, info.num_workers

        rng = np.random.default_rng(
            ((self.base_seed * 1_000_003) ^ (worker_id * 2_718_281)) & 0xFFFFFFFF)

        per_worker = {}
        for fk, keys in self.clips_by_factor.items():
            per_worker[fk] = keys[worker_id::num_workers] if keys else []
        active_factors = [f for f in self.factors if per_worker[f]]
        if not active_factors:
            return
        active_weights = np.array(
            [self.weights[self.factors.index(f)] for f in active_factors], dtype=np.float64)
        active_weights /= active_weights.sum()

        tar_cache = {}

        def _get_mp4_bytes(clip_key):
            tar_path, base = self.mp4_index[clip_key]
            if tar_path not in tar_cache:
                tar_cache[tar_path] = tarfile.open(tar_path, "r")
            tar = tar_cache[tar_path]
            mp4_member = tar.getmember(f"{base}.mp4")
            return tar.extractfile(mp4_member).read()

        try:
            with tempfile.TemporaryDirectory(prefix="m09c_stream_") as tmp:
                n_emitted = 0
                while self.steps_per_epoch is None or n_emitted < self.steps_per_epoch:
                    factor_type = active_factors[
                        rng.choice(len(active_factors), p=active_weights)]
                    clip_key = per_worker[factor_type][
                        rng.integers(len(per_worker[factor_type]))]

                    if factor_type == "D_I":
                        # iter10: D_I streaming. Generate tubes on-demand from
                        # (mp4_bytes, mask.npz); falls back to legacy disk path
                        # when interaction_cfg not provided (pre-iter10 callers).
                        if self.interaction_cfg is not None:
                            mp4_bytes = _get_mp4_bytes(clip_key)
                            tubes = stream_interaction_tubes(
                                mp4_bytes=mp4_bytes,
                                mask_npz_path=self.mask_index[clip_key],
                                interaction_cfg=self.interaction_cfg,
                                num_frames=self.num_frames,
                                tmp_dir=tmp,
                                clip_key=clip_key,
                            )
                            if not tubes:
                                # Clip lost all tubes to blacklist — re-sample next step.
                                continue
                            frames_uint8 = tubes[rng.integers(len(tubes))]
                        else:
                            tubes = self.di_legacy_index[clip_key]
                            tube_path = tubes[rng.integers(len(tubes))]
                            frames_uint8 = np.load(tube_path)
                    else:
                        mp4_bytes = _get_mp4_bytes(clip_key)
                        frames_uint8 = stream_factor(
                            mp4_bytes=mp4_bytes,
                            mask_npz_path=self.mask_index[clip_key],
                            factor_type=factor_type,
                            factor_cfg=self.factor_cfg,
                            num_frames=self.num_frames,
                            tmp_dir=tmp,
                            clip_key=clip_key,
                        )

                    tensor = tensor_from_factor_array(
                        frames_uint8, self.num_frames, self.crop_size)
                    yield {
                        "tensor": tensor,
                        "factor_type": factor_type,
                        "clip_key": clip_key,
                    }
                    n_emitted += 1
        finally:
            for tar_path, tar in tar_cache.items():
                try:
                    tar.close()
                except (OSError, tarfile.TarError) as e:
                    print(f"  StreamingFactorDataset: error closing {tar_path}: {e}")


# ═════════════════════════════════════════════════════════════════════════
# MID-TRAINING PROBE EVAL (Prec@K / mAP@K / Cycle@K with BCa 95% CI)
# ═════════════════════════════════════════════════════════════════════════
#
# Purpose: at stage boundaries, embed a held-out probe set through the CURRENT
# student and compute the same retrieval metrics the D.4 decision gate uses.
# Watches Surgery > Frozen emerge (or not) across the 3 stages without waiting
# for the full m05+m06 re-run cycle.
#
# Contract (technique-agnostic):
#   - Input:  student (vjepa2 VisionTransformer), pre-decoded probe tensors,
#             cfg dict, device.
#   - Output: dict with {prec_at_k, map_at_k, cycle_at_k} each {mean, ci_half}
#             and num_clips.
#   - No persistent state mutation: train()/eval() + return_hierarchical toggled
#     then restored under try/finally so the stage loop continues cleanly.
#
# Pooling matches m05_vjepa_embed.py:242 (outputs.mean(dim=1) over patch dim).
# Deterministic preprocess (center-crop + ImageNet-norm, no aug) so mid-stage
# deltas track the encoder, not the augmentation RNG.


def _probe_preprocess(video_uint8: torch.Tensor, crop_size: int) -> torch.Tensor:
    """Deterministic probe pipeline: center-crop → resize → ImageNet-normalize.

    video_uint8: (T, C, H, W) uint8 from decode_video_bytes().
    Returns: (T, C, crop_size, crop_size) float32, ImageNet-normalized.
    """
    _, _, H, W = video_uint8.shape
    side = min(H, W)
    top = (H - side) // 2
    left = (W - side) // 2
    video = video_uint8[:, :, top:top + side, left:left + side].float() / 255.0
    video = F.interpolate(video, size=(crop_size, crop_size),
                          mode="bilinear", align_corners=False)
    return (video - IMAGENET_MEAN.to(video.device)) / IMAGENET_STD.to(video.device)


def build_probe_clips(probe_subset_path: str, probe_local_data: str,
                      probe_tags_path: str, num_frames: int, crop_size: int,
                      subset_keys_override: set = None) -> list:
    """Decode + preprocess probe clips ONCE upfront. Returns list of
    (clip_key, tag_dict, tensor[T,C,H,W]).

    Tag alignment: Path(clip_key).name == tag["source_file"]. Clips without a
    matching tag record are skipped (not fatal — probe is best-effort signal).
    Heavy: 1K val_1k clips take ~5-10 min to decode via PyAV. Cost amortized
    across multiple probe calls.

    subset_keys_override: if provided (e.g., m09c held-out 10% split), skip the
    JSON load and use these keys directly. Lets callers plumb an in-memory split
    without writing a temp JSON to disk.
    """
    if subset_keys_override is not None:
        subset_keys = set(subset_keys_override)
    else:
        subset_keys = set(json.load(open(probe_subset_path))["clip_keys"])
    tags_list = json.load(open(probe_tags_path))
    # Fail-loud: tag records without "source_file" are malformed — skip with explicit test, no .get default.
    tag_by_source = {t["source_file"]: t for t in tags_list if "source_file" in t}

    tmp_dir = tempfile.mkdtemp(prefix="probe_decode_")
    clips = []
    n_no_tag = 0
    try:
        clip_q, tar_stop, _reader = iter_clips_parallel(probe_local_data, subset_keys=subset_keys)
        while True:
            try:
                item = clip_q.get(timeout=120)
            except queue.Empty:
                break
            if item is None:
                break
            clip_key, mp4_bytes = item
            if not mp4_bytes:
                continue
            source_file = Path(clip_key).name
            if source_file not in tag_by_source:
                n_no_tag += 1
                continue
            tag = tag_by_source[source_file]
            video_u8 = decode_video_bytes(mp4_bytes, tmp_dir, clip_key, num_frames)
            if video_u8 is None:
                continue
            tensor = _probe_preprocess(video_u8, crop_size)
            clips.append((clip_key, tag, tensor))
        tar_stop.set()
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print(f"  [probe] decoded {len(clips)} clips ({n_no_tag} skipped — no tag match)")
    if len(clips) < 100:
        print(f"  WARNING: probe has only {len(clips)} clips — bootstrap CI will be wide (N<100)")
    return clips


@torch.no_grad()
def run_probe_eval(student, probe_clips: list, cfg: dict, device: torch.device,
                   k: int, bootstrap_iter: int) -> dict:
    """Embed probe clips → Prec@K / mAP@K / Cycle@K with BCa 95% CI.

    Reuses utils.bootstrap vectorized per-clip functions so numbers are
    directly comparable to the D.4 decision gate (modulo deterministic probe
    preprocessing vs m05's augmented val-time transforms).

    Forward micro-batching: AdaptiveBatchSizer wired per CLAUDE.md B35 +
    errors_N_fixes.md #47 (universal infra, no hardcoded sub_batch). Sizer
    params come from pipeline.yaml — same keys m05 uses:
      - initial_size = gpu.inference_vjepa_initial_bs (safe start)
      - max_size     = gpu.inference_adapted_bs (cap — guards CPU queue + recompile)
      - memory_cap   = gpu.gpu_memory_target (universal 0.85)
    Forward-only (@torch.no_grad), so OOM recovery is clean: shrink → retry
    same micro, no partial-grad state to discard.

    Pooling matches m05:242 — outputs.mean(dim=1) over patch dim → (B, D=1664).
    Returns {"prec_at_k": {mean, ci_half, ci_lo, ci_hi}, ..., "num_clips": N}.
    """
    from utils.bootstrap import (
        bootstrap_ci, encode_tags_to_labels,
        per_clip_prec_at_k, per_clip_map_at_k, per_clip_cycle_at_k,
    )

    n = len(probe_clips)
    if n < 10:
        # Fail-loud: stable BCa CI needs N>=10. Caller wraps in try/except and
        # logs a WARN. Previously returned a dict with None values — that let
        # trajectory stats silently degrade. No defaults, no fallback.
        raise ValueError(
            f"probe N={n} too small for stable 95% BCa CI (needs N>=10). "
            f"Check probe.subset JSON clip_keys list + probe.local_data TAR coverage."
        )

    _gpu = get_pipeline_config()["gpu"]
    # iter11 perf fix — start at max_size (not initial_bs). The ramp from 8→44 caused
    # ~37 torch.compile recompiles per probe (~30 s each = 18 min/probe × 10 probes/ep =
    # 3 h wasted per epoch on v2 POC log, 2026-04-24). Starting at max=44 hits the
    # training-side compile cache (training forward already used shape = adapted_bs).
    # OOM fallback in the while-loop below ramps DOWN via sizer.on_oom() if surprise OOM.
    sizer = AdaptiveBatchSizer(
        initial_size=_gpu["inference_adapted_bs"],   # = max_size; skip ramp
        min_size=1,
        max_size=_gpu["inference_adapted_bs"],
        memory_cap=_gpu["gpu_memory_target"],
    )
    print(f"  [probe] AdaptiveBatchSizer: start={sizer.size}, "
          f"max={sizer.max_size}, cap={sizer.memory_cap:.0%} (iter11 no-ramp)")

    was_training = student.training
    had_hier = getattr(student, "return_hierarchical", None)
    student.eval()
    if had_hier is not None:
        student.return_hierarchical = False

    try:
        model_dtype = next(student.parameters()).dtype
        tags = [t for _, t, _ in probe_clips]
        emb_list = []
        i = 0
        print(f"  [probe] encoding {n} clips...", flush=True)
        while i < n:
            end = min(i + sizer.size, n)
            batch = torch.stack([c for _, _, c in probe_clips[i:end]])
            batch = batch.permute(0, 2, 1, 3, 4).to(device=device, dtype=model_dtype)
            try:
                out = student(batch)
                emb_list.append(out.mean(dim=1).float().cpu().numpy())
                sizer.after_batch_success()
                i = end
            except torch.cuda.OutOfMemoryError:
                cuda_cleanup()
                if not sizer.on_oom():
                    raise RuntimeError(
                        f"Probe OOM at min sub-batch={sizer.min_size} (N={n}). "
                        f"Student + activations don't fit even at BS=1 on this GPU. "
                        f"Reduce inference_vjepa_initial_bs in pipeline.yaml or run "
                        f"probe on larger hardware."
                    ) from None
                # retry same i at shrunken sizer.size
        embeddings = np.concatenate(emb_list, axis=0)
    finally:
        if had_hier is not None:
            student.return_hierarchical = had_hier
        if was_training:
            student.train()

    # L2-normalize: FAISS IndexFlatL2 on normalized vecs ≡ cosine rank.
    norms = np.linalg.norm(embeddings, axis=1, keepdims=True) + 1e-8
    embeddings = (embeddings / norms).astype(np.float32)

    # N=1K: IndexFlatL2 is exact + fastest; skip IVF. CPU index fine for this size.
    import faiss
    index = faiss.IndexFlatL2(embeddings.shape[1])
    index.add(embeddings)
    _D, I = index.search(embeddings, k + 1)  # col 0 = self

    label_arrays = encode_tags_to_labels(tags, ["scene_type"])
    prec_scores = per_clip_prec_at_k(I, tags, k, field="scene_type", label_arrays=label_arrays)
    map_scores = per_clip_map_at_k(I, tags, k, field="scene_type", label_arrays=label_arrays) * 100
    cycle_scores = per_clip_cycle_at_k(I, k) * 100

    return {
        "num_clips": n,
        "prec_at_k": bootstrap_ci(prec_scores, n_boot=bootstrap_iter),
        "map_at_k": bootstrap_ci(map_scores, n_boot=bootstrap_iter),
        "cycle_at_k": bootstrap_ci(cycle_scores, n_boot=bootstrap_iter),
    }


@torch.no_grad()
def run_probe_val_loss(student, teacher, predictor, probe_clips: list,
                       mask_generators: list, cfg: dict,
                       device: torch.device) -> dict:
    """Compute JEPA val-loss on the decoded probe clips (optimization-trajectory companion
    to run_probe_eval's downstream retrieval metrics). Same masked-token L1 + dense-context
    loss used during training, evaluated on held-out val_1k clips. Cheap (~6 s at N=1000).

    Contract: student's return_hierarchical MUST be True during this call (predictor needs
    hierarchical output). Caller-safe: train() / eval() toggled and restored.

    Returns {"jepa_loss", "masked_loss", "context_loss", "n_val_clips"}.
    """
    n = len(probe_clips)
    if n < 10:
        raise ValueError(f"probe val-loss N={n} too small for stable mean")

    was_training = student.training
    had_hier = getattr(student, "return_hierarchical", None)
    student.eval()
    if had_hier is not None:
        student.return_hierarchical = True   # predictor needs hierarchical output
    teacher_was_training = teacher.training
    predictor_was_training = predictor.training
    teacher.eval()
    predictor.eval()

    _gpu = get_pipeline_config()["gpu"]
    # iter11 perf fix — see run_probe_eval note above. Same reasoning applies to
    # probe-val-loss: skip ramp; start at max=adapted_bs; OOM retry ramps down if needed.
    sizer = AdaptiveBatchSizer(
        initial_size=_gpu["inference_adapted_bs"],   # = max_size; skip ramp
        min_size=1, max_size=_gpu["inference_adapted_bs"],
        memory_cap=_gpu["gpu_memory_target"])

    mp_cfg = cfg["mixed_precision"]
    dtype = getattr(torch, mp_cfg["dtype"])
    loss_exp = cfg["optimization"]["loss_exp"]
    embed_dim = cfg["model"]["embed_dim"]
    n_levels = cfg["model"]["n_output_distillation"]
    predict_all = cfg["model"]["predict_all"]

    total_j, total_m, total_c, n_seen = 0.0, 0.0, 0.0, 0

    try:
        i = 0
        while i < n:
            end = min(i + sizer.size, n)
            micro_bs = end - i
            batch = torch.stack([c for _, _, c in probe_clips[i:end]])
            batch = batch.permute(0, 2, 1, 3, 4).to(device=device, dtype=dtype)
            try:
                all_menc, all_mpred = [], []
                for mg in mask_generators:
                    me, mp = mg(micro_bs)
                    all_menc.append(me.to(device))
                    all_mpred.append(mp.to(device))
                with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                    h = teacher(batch)
                    if h.size(-1) == n_levels * embed_dim:
                        chunks = [F.layer_norm(h[:, :, lvl * embed_dim:(lvl + 1) * embed_dim], (embed_dim,))
                                  for lvl in range(n_levels)]
                        h = torch.cat(chunks, dim=2)
                    else:
                        h = F.layer_norm(h, (h.size(-1),))
                    pf, pc = [], []
                    for k, (me, mp) in enumerate(zip(all_menc, all_mpred)):
                        z = student(batch, masks=[me])
                        out = predictor(z, [me], [mp], mask_index=k)
                        if isinstance(out, tuple) and len(out) == 2:
                            pf.append(out[0]); pc.append(out[1])
                        else:
                            pf.append(out)
                    jl, lm, lc = compute_jepa_loss(pf, pc, h, all_mpred, all_menc,
                                                   loss_exp, predict_all, lambda_context=0.5)
                total_j += jl.item() * micro_bs
                total_m += lm.item() * micro_bs
                total_c += lc.item() * micro_bs
                n_seen += micro_bs
                sizer.after_batch_success()
                i = end
            except torch.cuda.OutOfMemoryError:
                cuda_cleanup()
                if not sizer.on_oom():
                    raise RuntimeError(
                        f"probe val-loss OOM at min sub-batch={sizer.min_size}"
                    ) from None
    finally:
        if had_hier is not None:
            student.return_hierarchical = had_hier
        if was_training:
            student.train()
        if teacher_was_training:
            teacher.train()
        if predictor_was_training:
            predictor.train()

    return {
        "jepa_loss": total_j / max(n_seen, 1),
        "masked_loss": total_m / max(n_seen, 1),
        "context_loss": total_c / max(n_seen, 1),
        "n_val_clips": n_seen,
    }


def compute_trajectory_stats(probe_history: list) -> dict:
    """Trajectory stats across stage boundaries.

    Single-probe-set regime: BWT degenerates to net improvement R[-1]-R[0] on
    Prec@K. Real GEM-BWT (per-task eval) would need separate D_L/D_A/D_I probe
    splits — deferred as future extension; this already flags regressions.

    Forgetting monitor: max_drop > 0 means some stage transition DROPPED Prec@K
    despite replay → the paper claim "replay prevents forgetting" fails on this
    run. User should inspect per-stage mode_mixture / warmup_pct.
    """
    # Fail-loud on structural issues — every probe_history entry must have the
    # full metric dict (run_probe_eval always returns it; missing = bug upstream).
    # Empty / single-entry history is a legit no-trajectory case (returns empty).
    if len(probe_history) < 2:
        return {"bwt_prec_at_k": None, "monotonic": None, "trajectory": []}

    traj = [r["prec_at_k"]["mean"] for r in probe_history]
    deltas = [traj[i] - traj[i - 1] for i in range(1, len(traj))]
    max_drop = -min(deltas) if min(deltas) < 0 else 0.0
    return {
        "bwt_prec_at_k": round(traj[-1] - traj[0], 4),
        "max_drop_prec_at_k": round(max_drop, 4),
        "monotonic": all(d >= 0 for d in deltas),
        "trajectory": [round(v, 4) for v in traj],
    }


def load_factor_clip(path: Path, num_frames: int, crop_size: int) -> torch.Tensor:
    """Load factor-patched clip from .npy → (T, C, H, W) float32 tensor, ImageNet-normalized.

    Delegates to tensor_from_factor_array so streaming + legacy paths share
    ONE normalization routine — guarantees bitwise parity.
    """
    from utils.factor_streaming import tensor_from_factor_array
    return tensor_from_factor_array(np.load(path), num_frames, crop_size)


def render_training_plots(
    probe_history: list,
    output_dir: Path,
    *,
    forgetting_threshold_pct: float,
    forgetting_patience: int,
    bwt_trigger_enabled: bool,
    bwt_ci_fraction: float,
    bwt_absolute_floor: float,
    bwt_patience: int,
    kill_state: dict,
    best_state: dict,
    probe_compute_val_loss: bool = True,
    verbose: bool = False,
) -> None:
    """Render probe_trajectory + m09_forgetting + m09_val_loss PNG/PDF from
    probe_history. Technique-agnostic — works for single-stage (m09b ExPLoRA)
    and multi-stage (m09c Surgery). Ported from m09c:_render_live_plots (iter11).

    Args:
        probe_history: list of probe records (each with global_step,
            prec_at_k/map_at_k/cycle_at_k {mean,ci_lo,ci_hi,ci_half},
            stage_idx, optional val_jepa_loss/val_masked_loss/val_context_loss,
            optional bwt, num_clips).
        output_dir: target dir for PNG/PDF writes.
        kill_state: {"triggered": bool} — used for title annotation only.
        best_state: {"global_step": int, "prec_at_k": float} — marker on forgetting plot.
            Pass {"global_step": -1, "prec_at_k": 0.0} to suppress marker.
        probe_compute_val_loss: if False, skips the val_jepa 3-panel plot.

    Needs ≥2 probe points; silent no-op below that. Each plot wrapped in
    try/except so rendering failure never kills training.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    if len(probe_history) < 2:
        return

    steps_ = [r["global_step"] for r in probe_history]

    # Plot 1: probe_trajectory.png/.pdf
    try:
        fig, axes = plt.subplots(3, 1, figsize=(9, 9), sharex=True)
        panels = [
            (axes[0], "prec_at_k",  "Prec@K (%)",  "#2E7D32"),
            (axes[1], "map_at_k",   "mAP@K (%)",   "#1565C0"),
            (axes[2], "cycle_at_k", "Cycle@K (%)", "#E65100"),
        ]
        for ax_p, metric, label, color in panels:
            means = [r[metric]["mean"] for r in probe_history]
            ci_los = [r[metric]["ci_lo"] for r in probe_history]
            ci_his = [r[metric]["ci_hi"] for r in probe_history]
            ax_p.plot(steps_, means, "o-", color=color, linewidth=2,
                      markersize=6, alpha=0.95)
            ax_p.fill_between(steps_, ci_los, ci_his, color=color, alpha=0.18)
            seen = set()
            for r in probe_history:
                if r["stage_idx"] not in seen:
                    ax_p.axvline(r["global_step"], color="gray",
                                 linestyle=":", alpha=0.5, linewidth=1)
                    seen.add(r["stage_idx"])
            ax_p.annotate(f"end={means[-1]:.2f}",
                          xy=(steps_[-1], means[-1]),
                          xytext=(5, 0), textcoords="offset points",
                          fontsize=8, color=color, va="center")
            ax_p.set_ylabel(label, color=color, fontsize=10, fontweight="bold")
            ax_p.tick_params(axis="y", labelsize=9, colors=color)
            ax_p.grid(True, alpha=0.3)
            mean_lo, mean_hi = min(means), max(means)
            pad = max((mean_hi - mean_lo) / 18, 0.005)
            ax_p.set_ylim(mean_lo - pad, mean_hi + pad)
        axes[-1].set_xlabel("Optimizer step", fontsize=10)
        fig.suptitle(
            f"Probe trajectory (N={probe_history[0]['num_clips']} val-split, "
            f"{len(probe_history)} probes, 95 % BCa CI) — per-panel y-axis auto-scaled",
            fontsize=11, fontweight="bold", y=0.995)
        plt.tight_layout()
        for ext in (".png", ".pdf"):
            plt.savefig(output_dir / f"probe_trajectory{ext}",
                        dpi=150 if ext == ".png" else None, bbox_inches="tight")
        plt.close()
        if verbose:
            print(f"  Saved: {output_dir / 'probe_trajectory.png'}")
    except Exception as e:
        if verbose:
            print(f"  [probe] WARN: trajectory plot failed: {e}")

    # Plot 2: m09_forgetting.png/.pdf
    try:
        fig, ax = plt.subplots(figsize=(8, 5))
        prec_ = [r["prec_at_k"]["mean"] for r in probe_history]
        running_max = []
        cur_max = -1.0
        for v in prec_:
            cur_max = max(cur_max, v)
            running_max.append(cur_max)
        strike_x, strike_y = [], []
        for s, p, m in zip(steps_, prec_, running_max):
            if m > 0 and p < m - forgetting_threshold_pct:
                strike_x.append(s)
                strike_y.append(p)
        ax.plot(steps_, prec_, "o-", color="#2E7D32", linewidth=2,
                label="Prec@K (held-out val)", markersize=5, alpha=0.9)
        ax.plot(steps_, running_max, "--", color="#1565C0", linewidth=1.5,
                label="running max", alpha=0.8)
        threshold_low = [m - forgetting_threshold_pct for m in running_max]
        ax.fill_between(steps_, threshold_low, running_max,
                        color="#FFA726", alpha=0.15,
                        label=f"forgetting tolerance ({forgetting_threshold_pct:.1f}pp)")
        if strike_x:
            ax.scatter(strike_x, strike_y, marker="x", s=100, color="#C62828",
                       label=f"forgetting strikes ({len(strike_x)})",
                       zorder=5, linewidths=2)
        seen = set()
        for r in probe_history:
            if r["stage_idx"] not in seen:
                ax.axvline(r["global_step"], color="gray",
                           linestyle=":", alpha=0.4, linewidth=1)
                seen.add(r["stage_idx"])
        if best_state.get("global_step", -1) >= 0:
            ax.axvline(best_state["global_step"], color="#2E7D32",
                       linestyle="-.", alpha=0.5, linewidth=1.5,
                       label=f"best ckpt (Prec@K={best_state['prec_at_k']:.2f})")
        ax2 = ax.twinx()
        bwt_vals = [r.get("bwt", r["prec_at_k"]["mean"] - prec_[0]) for r in probe_history]
        ax2.plot(steps_, bwt_vals, "s-", color="#8E24AA", linewidth=1.8,
                 markersize=4, alpha=0.9, label=f"BWT (latest={bwt_vals[-1]:+.2f} pp)")
        ax2.axhline(0.0, color="#8E24AA", linestyle=":", alpha=0.4, linewidth=1)
        if bwt_trigger_enabled and probe_history:
            latest_ci = probe_history[-1]["prec_at_k"]["ci_half"]
            ci_thr_vals = [-(bwt_ci_fraction * r["prec_at_k"]["ci_half"]) for r in probe_history]
            ax2.plot(steps_, ci_thr_vals, color="#C62828", linestyle="--",
                     alpha=0.6, linewidth=1,
                     label=f"ci-threshold (−{bwt_ci_fraction:.2f}×CI_half, now={-bwt_ci_fraction*latest_ci:+.2f})")
            ax2.axhline(-bwt_absolute_floor, color="#E65100", linestyle=":",
                        alpha=0.7, linewidth=1.2,
                        label=f"abs floor (−{bwt_absolute_floor:.2f} pp × {bwt_patience} probes)")
        ax2.set_ylabel("BWT (pp) = Prec@K − Prec@K[first]", color="#8E24AA")
        ax2.tick_params(axis="y", labelcolor="#8E24AA")
        prec_lo_tight = min(prec_)
        prec_hi_tight = max(max(prec_), max(running_max))
        prec_pad = max((prec_hi_tight - prec_lo_tight) / 18, 0.005)
        ax.set_ylim(prec_lo_tight - prec_pad, prec_hi_tight + prec_pad)
        bwt_lo_tight = min(bwt_vals)
        bwt_hi_tight = max(bwt_vals)
        bwt_pad = max((bwt_hi_tight - bwt_lo_tight) / 18, 0.005)
        ax2.set_ylim(bwt_lo_tight - bwt_pad, bwt_hi_tight + bwt_pad)
        kill_msg = " — TRIGGERED" if kill_state.get("triggered") else ""
        ax.set_xlabel("Optimizer step")
        ax.set_ylabel("Prec@K (%)")
        ax.set_title(
            f"Forgetting monitor (N={probe_history[0]['num_clips']}, "
            f"patience={forgetting_patience}, threshold={forgetting_threshold_pct:.1f}pp{kill_msg})")
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2,
                  loc="upper left", bbox_to_anchor=(1.15, 1.0),
                  fontsize=7, framealpha=0.95,
                  title="legend", title_fontsize=8)
        ax.grid(True, alpha=0.3)
        for ext in (".png", ".pdf"):
            plt.savefig(output_dir / f"m09_forgetting{ext}",
                        dpi=150 if ext == ".png" else None, bbox_inches="tight")
        plt.close()
        if verbose:
            print(f"  Saved: {output_dir / 'm09_forgetting.png'}")
    except Exception as e:
        if verbose:
            print(f"  [probe] WARN: forgetting plot failed: {e}")

    # Plot 3: m09_val_loss.png/.pdf — 3-panel stacked (optional).
    # m09b uses "val_jepa_loss"/"masked_loss"/"context_loss" keys; m09c historically
    # writes "val_jepa_loss"/"val_masked_loss"/"val_context_loss". Support both.
    if probe_compute_val_loss and probe_history:
        # Auto-detect key naming convention from first record with val_jepa_loss.
        sample = next((r for r in probe_history if "val_jepa_loss" in r), None)
        if sample is None:
            return
        if "val_masked_loss" in sample:
            panel_keys = [("val_jepa_loss", "JEPA total (L1)", "#C62828"),
                          ("val_masked_loss", "masked loss", "#1565C0"),
                          ("val_context_loss", "context loss", "#2E7D32")]
        elif "masked_loss" in sample:
            panel_keys = [("val_jepa_loss", "JEPA total (L1)", "#C62828"),
                          ("masked_loss", "masked loss", "#1565C0"),
                          ("context_loss", "context loss", "#2E7D32")]
        else:
            return  # only val_jepa_loss present — skip 3-panel
        try:
            fig, axes = plt.subplots(3, 1, figsize=(9, 9), sharex=True,
                                     gridspec_kw={"hspace": 0.15})
            stage_boundaries = []
            seen = set()
            for r in probe_history:
                if r["stage_idx"] not in seen:
                    stage_boundaries.append(r["global_step"])
                    seen.add(r["stage_idx"])
            for (key, ylabel, color), ax_i in zip(panel_keys, axes):
                vals = [r[key] for r in probe_history]
                ax_i.plot(steps_, vals, "o-", color=color, linewidth=2,
                          markersize=6, alpha=0.9)
                for sb in stage_boundaries:
                    ax_i.axvline(sb, color="gray", linestyle=":", alpha=0.4, linewidth=1)
                ax_i.set_ylabel(ylabel, color=color, fontsize=10, fontweight="bold")
                ax_i.tick_params(axis="y", labelcolor=color)
                ax_i.margins(y=0.05)
                ax_i.grid(True, alpha=0.3)
                if vals:
                    ax_i.annotate(f"end={vals[-1]:.4f}", xy=(steps_[-1], vals[-1]),
                                  xytext=(5, 0), textcoords="offset points",
                                  fontsize=8, color=color, va="center")
            axes[-1].set_xlabel("Optimizer step")
            axes[0].set_title(
                f"JEPA val-loss (N={probe_history[0]['num_clips']} val-split, "
                f"{len(probe_history)} probes) — per-panel y-axis auto-scaled")
            for ext in (".png", ".pdf"):
                plt.savefig(output_dir / f"m09_val_loss{ext}",
                            dpi=150 if ext == ".png" else None, bbox_inches="tight")
            plt.close()
            if verbose:
                print(f"  Saved: {output_dir / 'm09_val_loss.png'}")
        except Exception as e:
            if verbose:
                print(f"  [probe] WARN: val-loss plot failed: {e}")
