_wandb:
    value:
        cli_version: 0.25.1
        e:
            axlmqnclsvoragqr0z9yzshuqvwpfbrg:
                args:
                    - --encoders
                    - vjepa,clip,dinov2,random,vjepa_lambda0_001,vjepa_lambda0_01,vjepa_lambda0_01_shuffled,vjepa_shuffled
                    - --SANITY
                codePath: src/m08b_compare.py
                codePathLocal: src/m08b_compare.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "34359738368"
                        used: "2518736896"
                email: kapilw25@gmail.com
                executable: /workspace/factorjepa/venv_walkindia/bin/python
                git:
                    commit: 945d9c312d7b9890220fa9a55d115935f0b24a26
                    remote: https://github.com/kapilw25/factorjepa.git
                gpu: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 24064
                      memoryTotal: "102641958912"
                      name: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
                      uuid: GPU-385fd64a-daf1-e235-0f52-ff35f2f5a5dd
                host: 2d5319172a4c
                memory:
                    total: "134098214912"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /workspace/factorjepa/src/m08b_compare.py
                python: CPython 3.12.13
                root: /workspace/factorjepa
                startedAt: "2026-04-04T14:42:16.810282Z"
                writerId: axlmqnclsvoragqr0z9yzshuqvwpfbrg
        m: []
        python_version: 3.12.13
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.13
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
FULL:
    value: false
POC:
    value: false
SANITY:
    value: true
encoders:
    value: vjepa,clip,dinov2,random,vjepa_lambda0_001,vjepa_lambda0_01,vjepa_lambda0_01_shuffled,vjepa_shuffled
no_wandb:
    value: false
subset:
    value: null
