"""
V-JEPA 2 continual pretraining on Indian urban clips (Ch10).
Student-teacher JEPA with EMA, L1 latent prediction, drift control.
GPU-only (requires vjepa2 package + CUDA).

SETUP (one-time): python -u src/m00c_sample_subset.py --POC --n 1000 --seed 99 --output data/val_1k.json

USAGE:
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --SANITY 2>&1 | tee logs/m09_pretrain_sanity.log
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --POC --subset data/subset_10k.json --val-subset data/val_1k.json \
        --local-data data/subset_10k_local --val-local-data data/val_1k_local \
        2>&1 | tee logs/m09_pretrain_poc.log
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --FULL --val-subset data/val_1k.json --local-data data/full_local \
        --val-local-data data/val_1k_local 2>&1 | tee logs/m09_pretrain_full.log

ABLATION (drift control lambda sweep — run sequentially or on 4 GPUs):
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --FULL --subset data/subset_10k.json --local-data data/subset_10k_local \
        --lambda-reg 0 2>&1 | tee logs/m09_lambda0.log
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --FULL --subset data/subset_10k.json --local-data data/subset_10k_local \
        --lambda-reg 0.001 2>&1 | tee logs/m09_lambda0_001.log
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --FULL --subset data/subset_10k.json --local-data data/subset_10k_local \
        --lambda-reg 0.01 2>&1 | tee logs/m09_lambda0_01.log
    python -u src/m09_pretrain.py --config configs/pretrain/vitg16_indian.yaml \
        --FULL --subset data/subset_10k.json --local-data data/subset_10k_local \
        --lambda-reg 0.1 2>&1 | tee logs/m09_lambda0_1.log
"""
import argparse
import copy
import csv
import gc
import glob
import json
import os
import queue
import sys
import tempfile
import threading
import time
from pathlib import Path

import numpy as np
import yaml
from tqdm import tqdm

# Add src to path for utils import
sys.path.insert(0, str(Path(__file__).parent))
from utils.config import (
    HF_DATASET_REPO, check_gpu,
    add_subset_arg, add_local_data_arg, get_output_dir, load_subset,
    get_pipeline_config,
)
from utils.data_download import ensure_local_data
from utils.wandb_utils import (
    add_wandb_args, init_wandb, log_metrics, finish_wandb,
)

import torch
import torch.nn.functional as F

# vjepa2 imports via shim (avoids src/ namespace collision)
from utils.vjepa2_imports import (
    get_vit_giant_xformers, get_vit_predictor,
    get_mask_generator, get_apply_masks,
)

# Constants
DEFAULT_CONFIG = "configs/pretrain/vitg16_indian.yaml"
CHECKPOINT_PREFIX = "m09_ckpt"
_pcfg = get_pipeline_config()
PREFETCH_QUEUE_SIZE = _pcfg["streaming"]["prefetch_queue_train"]
DECODE_WORKERS = _pcfg["streaming"]["decode_workers_train"]
MAX_STREAM_RETRIES = _pcfg["streaming"]["max_retries"]

# Reuse data loading from m05
from m05_vjepa_embed import (
    get_clip_key, _create_stream, decode_video_bytes,
)


# ═════════════════════════════════════════════════════════════════════════
# CONFIG
# ═════════════════════════════════════════════════════════════════════════

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


def merge_config_with_args(cfg: dict, args) -> dict:
    if args.subset:
        cfg["data"]["subset"] = args.subset
    if getattr(args, "local_data", None):
        cfg["data"]["local_data"] = args.local_data
    if args.SANITY:
        mode_key = "sanity"
    elif args.POC:
        mode_key = "poc"
    else:
        mode_key = "full"
    cfg["optimization"]["max_epochs"] = cfg["optimization"]["max_epochs"][mode_key]
    if args.batch_size is not None:
        cfg["optimization"]["batch_size"] = args.batch_size
    if args.max_epochs is not None:
        cfg["optimization"]["max_epochs"] = args.max_epochs
    if args.lambda_reg is not None:
        cfg["drift_control"]["lambda_reg"] = args.lambda_reg
        if args.lambda_reg == 0:
            cfg["drift_control"]["enabled"] = False

    # Output dir: base/m09_lambda{value}/ for ablation isolation
    base_out = get_output_dir(args.subset, sanity=args.SANITY)
    lam = cfg["drift_control"]["lambda_reg"]
    lam_str = f"{lam:g}".replace(".", "_")  # 0.0→"0", 0.01→"0_01" (no trailing .0)
    cfg["checkpoint"]["output_dir"] = str(base_out / f"m09_lambda{lam_str}")
    return cfg


# ═════════════════════════════════════════════════════════════════════════
# DATA LOADING
# ═════════════════════════════════════════════════════════════════════════

def load_val_subset(val_subset_path: str) -> set:
    """Load val subset clip keys from JSON (generated by m00c_sample_subset.py)."""
    if not val_subset_path:
        return set()
    p = Path(val_subset_path)
    if not p.exists():
        print(f"FATAL: Val subset file not found: {p}")
        sys.exit(1)
    with open(p) as f:
        data = json.load(f)
    keys = set(data["clip_keys"])
    print(f"[VAL] Loaded val subset: {len(keys):,} clips from {p.name}")
    return keys


def augment_clip_consistent(video_tensor: torch.Tensor, cfg_aug: dict,
                            crop_size: int) -> torch.Tensor:
    """Video-consistent augmentation: same random crop applied to ALL T frames."""
    import torchvision.transforms as TT

    T_frames, C, H, W = video_tensor.shape
    scale = cfg_aug.get("random_resize_scale", [0.3, 1.0])
    ratio = cfg_aug.get("random_resize_ratio", [0.75, 1.35])

    i, j, h, w = TT.RandomResizedCrop.get_params(
        video_tensor[0], scale=scale, ratio=ratio)

    video = video_tensor.float() / 255.0
    video = video[:, :, i:i+h, j:j+w]
    video = F.interpolate(video, size=(crop_size, crop_size),
                          mode='bilinear', align_corners=False)

    if torch.rand(1).item() < cfg_aug.get("horizontal_flip", 0.5):
        video = video.flip(-1)

    return video  # (T, C, crop_size, crop_size)


def producer_thread(cfg: dict, q: queue.Queue, stop_event: threading.Event,
                    train_keys: set, processed_steps: int):
    """Stream WebDataset, decode videos, augment, enqueue batches (multi-epoch)."""
    from concurrent.futures import ThreadPoolExecutor

    # Prevent ATen thread oversubscription (CLAUDE.md rule #12)
    torch.set_num_threads(1)

    batch_size = cfg["optimization"]["batch_size"]
    num_frames = cfg["data"]["num_frames"]
    crop_size = cfg["data"]["crop_size"]
    local_data = cfg["data"].get("local_data")
    cfg_aug = cfg.get("augmentation", {})
    retries = 0
    epoch = 0

    tmp_dir = tempfile.mkdtemp(prefix="m09_")

    try:
        while not stop_event.is_set():
            try:
                epoch += 1
                if epoch > 1:
                    print(f"  Producer: starting epoch {epoch}")
                ds = _create_stream(0, local_data=local_data)
                pending_bytes, pending_keys = [], []

                for example in ds:
                    if stop_event.is_set():
                        break

                    clip_key = get_clip_key(example)
                    if train_keys and clip_key not in train_keys:
                        continue

                    mp4_data = example.get("mp4", b"")
                    mp4_bytes = mp4_data["bytes"] if isinstance(mp4_data, dict) else mp4_data
                    if not mp4_bytes:
                        continue

                    pending_bytes.append(mp4_bytes)
                    pending_keys.append(clip_key)

                    if len(pending_bytes) >= batch_size:
                        with ThreadPoolExecutor(max_workers=DECODE_WORKERS) as pool:
                            futures = [
                                pool.submit(decode_video_bytes, b, tmp_dir, k, num_frames)
                                for b, k in zip(pending_bytes, pending_keys)
                            ]
                            results = [(f.result(), k) for f, k in zip(futures, pending_keys)]

                        batch_tensors = [t for t, k in results if t is not None]
                        batch_keys = [k for t, k in results if t is not None]

                        if batch_tensors:
                            augmented = []
                            for vt in batch_tensors:
                                aug = augment_clip_consistent(vt, cfg_aug, crop_size)
                                augmented.append(aug)

                            batch = torch.stack(augmented, dim=0)  # (B, T, C, H, W)
                            batch = batch.permute(0, 2, 1, 3, 4)  # (B, C, T, H, W)
                            q.put(("batch", batch, batch_keys[:]))

                        pending_bytes, pending_keys = [], []
                        retries = 0

                # Handle final partial batch
                if pending_bytes and not stop_event.is_set():
                    with ThreadPoolExecutor(max_workers=DECODE_WORKERS) as pool:
                        futures = [
                            pool.submit(decode_video_bytes, b, tmp_dir, k, num_frames)
                            for b, k in zip(pending_bytes, pending_keys)
                        ]
                        results = [(f.result(), k) for f, k in zip(futures, pending_keys)]

                    batch_tensors = [t for t, k in results if t is not None]
                    batch_keys = [k for t, k in results if t is not None]
                    if batch_tensors:
                        augmented = [augment_clip_consistent(vt, cfg_aug, crop_size)
                                     for vt in batch_tensors]
                        batch = torch.stack(augmented, dim=0).permute(0, 2, 1, 3, 4)
                        q.put(("batch", batch, batch_keys[:]))

                # Loop to next epoch (don't break — training needs multiple passes)

            except (ConnectionError, TimeoutError, OSError) as e:
                retries += 1
                if retries > MAX_STREAM_RETRIES:
                    print(f"  ERROR: stream failed after {MAX_STREAM_RETRIES} retries: {e}")
                    break
                wait = min(2 ** retries, 60)
                print(f"  WARN: stream error ({e}), retry {retries}/{MAX_STREAM_RETRIES} in {wait}s")
                time.sleep(wait)
    finally:
        import shutil
        shutil.rmtree(tmp_dir, ignore_errors=True)
        q.put(("done", None, None))


# ═════════════════════════════════════════════════════════════════════════
# MODEL SETUP (Q1-Q5 corrected: no wrappers, vit_giant_xformers, RoPE)
# ═════════════════════════════════════════════════════════════════════════

def build_model(cfg: dict, device: torch.device) -> dict:
    """Build student encoder, teacher encoder (EMA), and predictor."""
    vit_giant_xformers = get_vit_giant_xformers()
    vit_predictor = get_vit_predictor()

    model_cfg = cfg["model"]
    data_cfg = cfg["data"]

    # Student encoder (Q1: use vit_giant_xformers, Q5: use_rope=True)
    student = vit_giant_xformers(
        img_size=(data_cfg["crop_size"], data_cfg["crop_size"]),
        patch_size=data_cfg["patch_size"],
        num_frames=data_cfg["num_frames"],
        tubelet_size=data_cfg["tubelet_size"],
        use_sdpa=True,
        use_silu=False,
        wide_silu=True,
        uniform_power=False,
        use_rope=model_cfg.get("use_rope", True),
        use_activation_checkpointing=model_cfg.get("use_activation_checkpointing", True),
    )

    # Load pretrained weights (Q3: target_encoder key, Q5: strip prefixes)
    project_root = Path(__file__).parent.parent
    ckpt_dir = project_root / "checkpoints"
    ckpt_path = ckpt_dir / "vjepa2_vitg384.pt"
    if ckpt_path.exists():
        print(f"Loading pretrained weights from {ckpt_path}")
        ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    else:
        print("Downloading pretrained weights via torch.hub...")
        url = "https://dl.fbaipublicfiles.com/vjepa2/vitg-384.pt"
        ckpt_dir.mkdir(parents=True, exist_ok=True)
        ckpt = torch.hub.load_state_dict_from_url(url, map_location="cpu",
                                                    model_dir=str(ckpt_dir))

    # Q3: Use target_encoder (EMA teacher = best quality starting point)
    if "target_encoder" in ckpt:
        state_dict = ckpt["target_encoder"]
    elif "encoder" in ckpt:
        state_dict = ckpt["encoder"]
    else:
        state_dict = ckpt

    # Q5: Strip DDP + wrapper prefixes
    state_dict = {k.replace("module.", "").replace("backbone.", ""): v
                  for k, v in state_dict.items()}

    msg = student.load_state_dict(state_dict, strict=False)
    total_keys = len(list(student.state_dict().keys()))
    loaded_keys = total_keys - len(msg.missing_keys)
    load_pct = loaded_keys / max(total_keys, 1) * 100
    print(f"Student loaded: {sum(p.numel() for p in student.parameters()):,} params "
          f"({loaded_keys}/{total_keys} keys = {load_pct:.0f}%)")
    if msg.missing_keys:
        # pos_embed is expected missing when using RoPE
        unexpected_missing = [k for k in msg.missing_keys if "pos_embed" not in k]
        if unexpected_missing:
            print(f"  WARNING: {len(unexpected_missing)} unexpected missing keys: "
                  f"{unexpected_missing[:5]}")
    if load_pct < 90:
        print(f"FATAL: Only {load_pct:.0f}% of student keys loaded. "
              f"Checkpoint likely incompatible.")
        print(f"  Checkpoint keys sample: {list(state_dict.keys())[:3]}")
        print(f"  Model keys sample:      {list(student.state_dict().keys())[:3]}")
        sys.exit(1)
    student = student.to(device)

    # Teacher (EMA copy, frozen)
    teacher = copy.deepcopy(student)
    for p in teacher.parameters():
        p.requires_grad = False
    teacher.eval()
    print(f"Teacher created (deepcopy of student)")

    # Predictor (Q4: num_mask_tokens, Q1: use_rope)
    predictor = vit_predictor(
        img_size=(data_cfg["crop_size"], data_cfg["crop_size"]),
        patch_size=data_cfg["patch_size"],
        num_frames=data_cfg["num_frames"],
        tubelet_size=data_cfg["tubelet_size"],
        embed_dim=model_cfg["embed_dim"],
        predictor_embed_dim=model_cfg["pred_embed_dim"],
        depth=model_cfg["pred_depth"],
        num_heads=model_cfg["pred_num_heads"],
        use_mask_tokens=True,
        num_mask_tokens=model_cfg.get("num_mask_tokens", 2),
        zero_init_mask_tokens=True,
        use_rope=model_cfg.get("use_rope", True),
        uniform_power=False,
        use_sdpa=True,
        use_silu=False,
        wide_silu=True,
        use_activation_checkpointing=model_cfg.get("use_activation_checkpointing", True),
    )

    # Q3: Load predictor weights if available
    if "predictor" in ckpt:
        pred_state = {k.replace("module.", "").replace("backbone.", ""): v
                      for k, v in ckpt["predictor"].items()}
        pred_msg = predictor.load_state_dict(pred_state, strict=False)
        pred_total = len(list(predictor.state_dict().keys()))
        pred_loaded = pred_total - len(pred_msg.missing_keys)
        pred_pct = pred_loaded / max(pred_total, 1) * 100
        print(f"Predictor loaded from checkpoint ({pred_loaded}/{pred_total} keys = {pred_pct:.0f}%)")
        if pred_pct < 50:
            print(f"  WARNING: Predictor only {pred_pct:.0f}% loaded — may train from near-random init")
    else:
        print("Predictor initialized randomly (no pretrained weights)")

    predictor = predictor.to(device)
    print(f"Predictor: {sum(p.numel() for p in predictor.parameters()):,} params")

    # Save initial params for drift control (on CPU to save ~4GB VRAM)
    init_params = {name: p.clone().detach().cpu()
                   for name, p in student.named_parameters()}

    del ckpt
    gc.collect()

    return {
        "student": student,
        "teacher": teacher,
        "predictor": predictor,
        "init_params": init_params,
    }


# ═════════════════════════════════════════════════════════════════════════
# MASKING (Q4: Use _MaskGenerator directly, not MaskCollator)
# ═════════════════════════════════════════════════════════════════════════

def build_mask_generators(cfg: dict) -> list:
    """Build one _MaskGenerator per mask config."""
    _MaskGenerator = get_mask_generator()

    data_cfg = cfg["data"]
    generators = []
    for m_cfg in cfg["mask"]:
        mg = _MaskGenerator(
            crop_size=(data_cfg["crop_size"], data_cfg["crop_size"]),
            num_frames=data_cfg["num_frames"],
            spatial_patch_size=(data_cfg["patch_size"], data_cfg["patch_size"]),
            temporal_patch_size=data_cfg["tubelet_size"],
            spatial_pred_mask_scale=m_cfg["spatial_scale"],
            temporal_pred_mask_scale=m_cfg["temporal_scale"],
            aspect_ratio=m_cfg["aspect_ratio"],
            npred=m_cfg["num_blocks"],
        )
        generators.append(mg)
    return generators


# ═════════════════════════════════════════════════════════════════════════
# LOSS (L1 latent prediction + drift control)
# ═════════════════════════════════════════════════════════════════════════

def compute_jepa_loss(pred_features: list, teacher_output: torch.Tensor,
                      masks_pred: list, loss_exp: float = 1.0) -> torch.Tensor:
    """L1 latent prediction loss on masked tokens (V-JEPA 2 convention).

    pred_features: list of predictor outputs, one per mask generator
    teacher_output: teacher forward on full clip (B, N_total, D)
    masks_pred: list of target mask tensors, one per mask generator
    """
    apply_masks = get_apply_masks()

    loss = torch.tensor(0.0, device=teacher_output.device)
    n = 0
    for pred_i, mask_i in zip(pred_features, masks_pred):
        # Extract teacher features at masked positions
        h_masked = apply_masks(teacher_output, [mask_i])  # (B, N_masked, D)
        loss += torch.mean(torch.abs(pred_i - h_masked) ** loss_exp) / loss_exp
        n += 1
    return loss / max(n, 1)


def compute_drift_loss(student: torch.nn.Module, init_params: dict,
                       lambda_reg: float) -> torch.Tensor:
    """L2 drift control: lambda * ||theta - theta_0||^2 (Sec 10.4)."""
    device = next(student.parameters()).device
    drift = torch.tensor(0.0, device=device)
    for name, param in student.named_parameters():
        if name in init_params:
            drift += torch.sum((param - init_params[name].to(device)) ** 2)
    return lambda_reg * drift


# ═════════════════════════════════════════════════════════════════════════
# EMA TEACHER UPDATE
# ═════════════════════════════════════════════════════════════════════════

@torch.no_grad()
def update_teacher_ema(student: torch.nn.Module, teacher: torch.nn.Module,
                       momentum: float):
    """EMA update: theta_bar <- tau * theta_bar + (1-tau) * theta"""
    params_s = list(student.parameters())
    params_t = list(teacher.parameters())
    torch._foreach_mul_(params_t, momentum)
    torch._foreach_add_(params_t, params_s, alpha=1.0 - momentum)


# ═════════════════════════════════════════════════════════════════════════
# OPTIMIZER & SCHEDULER
# ═════════════════════════════════════════════════════════════════════════

def build_optimizer(student, predictor, cfg_opt: dict):
    base_lr = cfg_opt["lr"]
    pred_lr = base_lr * cfg_opt["pred_lr_multiplier"]
    wd = cfg_opt["weight_decay"]

    def split_params(module, lr):
        decay, no_decay = [], []
        for name, p in module.named_parameters():
            if not p.requires_grad:
                continue
            if "bias" in name or "norm" in name or "ln" in name:
                no_decay.append(p)
            else:
                decay.append(p)
        return [
            {"params": decay, "lr": lr, "weight_decay": wd},
            {"params": no_decay, "lr": lr, "weight_decay": 0.0},
        ]

    param_groups = split_params(student, base_lr) + split_params(predictor, pred_lr)
    return torch.optim.AdamW(param_groups, betas=tuple(cfg_opt["betas"]),
                              eps=cfg_opt["eps"])


def build_scheduler(optimizer, cfg_opt: dict, total_steps: int):
    # Cap warmup to 10% of total steps (avoids never leaving warmup on short runs)
    warmup_steps = min(cfg_opt["warmup_steps"], max(1, total_steps // 10))
    min_lr = cfg_opt["min_lr"]
    base_lr = cfg_opt["lr"]

    def lr_lambda(step):
        if step < warmup_steps:
            return step / max(warmup_steps, 1)
        progress = (step - warmup_steps) / max(total_steps - warmup_steps, 1)
        return max(min_lr / base_lr, 0.5 * (1 + np.cos(np.pi * progress)))

    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)


def update_weight_decay(optimizer, cfg_opt: dict, step: int, total_steps: int):
    """Cosine weight decay schedule (matches Meta's CosineWDSchedule).

    Ramps WD from weight_decay to final_weight_decay over training.
    If both are equal (default: 0.04), this is a no-op.
    """
    initial_wd = cfg_opt["weight_decay"]
    final_wd = cfg_opt.get("final_weight_decay", initial_wd)
    if initial_wd == final_wd:
        return  # no-op: fixed WD
    progress = step / max(total_steps, 1)
    new_wd = final_wd + 0.5 * (initial_wd - final_wd) * (1 + np.cos(np.pi * progress))
    for group in optimizer.param_groups:
        if group.get("weight_decay", 0) > 0:  # don't touch no_decay groups
            group["weight_decay"] = new_wd


# ═════════════════════════════════════════════════════════════════════════
# VALIDATION (JEPA L1 loss on held-out val clips)
# ═════════════════════════════════════════════════════════════════════════

def run_validation(student, teacher, predictor, mask_generators,
                   val_batches: list, cfg: dict, device: torch.device,
                   step: int) -> float:
    """Compute JEPA L1 loss on val clips. Same as training loss, different data.

    Returns mean val loss (scalar).
    """
    student.eval()
    predictor.eval()

    mp_cfg = cfg["mixed_precision"]
    dtype = getattr(torch, mp_cfg["dtype"])
    loss_exp = cfg["optimization"]["loss_exp"]
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch_clips in val_batches:
            batch_clips = batch_clips.to(device)
            actual_bs = batch_clips.shape[0]

            # Generate masks (same as training)
            all_masks_enc, all_masks_pred = [], []
            for mg in mask_generators:
                m_enc, m_pred = mg(actual_bs)
                all_masks_enc.append(m_enc.to(device))
                all_masks_pred.append(m_pred.to(device))

            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                # Teacher: all tokens
                h = teacher(batch_clips)

                # Student + Predictor per mask generator
                pred_features = []
                for i, (m_enc, m_pred) in enumerate(zip(all_masks_enc, all_masks_pred)):
                    z = student(batch_clips, masks=[m_enc])
                    p = predictor(z, [m_enc], [m_pred], mask_index=i)
                    pred_features.append(p)

                # L1 loss (same as training, no drift control)
                jepa_loss = compute_jepa_loss(pred_features, h, all_masks_pred, loss_exp)

            total_loss += jepa_loss.item()
            n_batches += 1

    val_loss = total_loss / max(n_batches, 1)
    print(f"  Step {step} | Val JEPA loss: {val_loss:.4f} ({len(val_batches)} batches)")

    student.train()
    predictor.train()
    return val_loss


# ═════════════════════════════════════════════════════════════════════════
# CHECKPOINT
# ═════════════════════════════════════════════════════════════════════════

def save_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler,
                              step: int, best_metric: float,
                              full: bool = True):
    """Save checkpoint. full=True includes optimizer (for resume), False is light (for selection)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(".tmp")
    ckpt = {
        "student": student.state_dict(),
        "teacher": teacher.state_dict(),
        "predictor": predictor.state_dict(),
        "step": step,
        "best_metric": best_metric,
    }
    if full:
        ckpt["optimizer"] = optimizer.state_dict()
        ckpt["scheduler"] = scheduler.state_dict()
        ckpt["scaler"] = scaler.state_dict() if scaler else None
    torch.save(ckpt, tmp_path)
    os.replace(tmp_path, path)


def cleanup_old_checkpoints(output_dir: Path, keep_n: int = 2):
    """Delete oldest m09_ckpt_step*.pt files, keeping only the last keep_n."""
    pattern = str(output_dir / f"{CHECKPOINT_PREFIX}_step*.pt")
    step_files = sorted(glob.glob(pattern),
                        key=lambda f: os.path.getmtime(f))
    if len(step_files) > keep_n:
        for old_file in step_files[:-keep_n]:
            os.remove(old_file)
            print(f"  Cleaned old checkpoint: {Path(old_file).name}")


def load_training_checkpoint(path: Path, student, teacher, predictor,
                              optimizer, scheduler, scaler) -> tuple:
    ckpt = torch.load(path, map_location="cuda", weights_only=False)
    student.load_state_dict(ckpt["student"])
    teacher.load_state_dict(ckpt["teacher"])
    predictor.load_state_dict(ckpt["predictor"])
    if "optimizer" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer"])
    if "scheduler" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler"])
    if scaler and ckpt.get("scaler"):
        scaler.load_state_dict(ckpt["scaler"])
    return ckpt["step"], ckpt.get("best_metric", float("inf"))


def export_student_for_eval(student, path: Path):
    """Export student encoder weights + metadata for m05/m06 re-evaluation."""
    from utils.config import VJEPA_MODEL_ID
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save({
        "student_state_dict": student.state_dict(),
        "model_id": VJEPA_MODEL_ID,  # base architecture for instantiation
        "type": "vjepa2_adapted",
    }, path)
    print(f"Exported student encoder: {path}")


# ═════════════════════════════════════════════════════════════════════════
# TRAINING LOOP
# ═════════════════════════════════════════════════════════════════════════

def train(cfg: dict, args):
    """Epoch-based training loop (proposal Sec 10.5)."""
    check_gpu()
    device = torch.device("cuda")

    # Reproducibility seeds (matches Meta's train.py lines 45-48, 152-154)
    import random
    seed = cfg["data"]["seed"]
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.backends.cudnn.benchmark = True

    # Disable auto GC, collect manually every 50 steps (matches Meta's sync_gc pattern)
    gc.disable()
    gc.collect()

    # Output-exists guard
    from utils.output_guard import verify_training_output
    output_dir = Path(cfg["checkpoint"]["output_dir"])
    student_path = output_dir / "student_encoder.pt"
    if verify_training_output(output_dir, min_epochs=cfg["optimization"]["max_epochs"]):
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    # Build model
    print("\n=== Building Model ===")
    models = build_model(cfg, device)
    student = models["student"]
    teacher = models["teacher"]
    predictor = models["predictor"]
    init_params = models["init_params"]

    student.train()
    predictor.train()

    # Build mask generators
    mask_generators = build_mask_generators(cfg)
    print(f"Mask generators: {len(mask_generators)} "
          f"(blocks: {[m['num_blocks'] for m in cfg['mask']]})")

    # Compute epoch geometry
    # Train: --subset keys minus val keys. Val: --val-subset keys (pre-sampled via m00c).
    subset_keys = load_subset(args.subset) if args.subset else set()
    val_key_set = load_val_subset(args.val_subset)

    # Exclude val keys from training (no leakage)
    if subset_keys and val_key_set:
        overlap = subset_keys & val_key_set
        if overlap:
            print(f"Excluding {len(overlap)} val clips from training set")
            train_keys = subset_keys - val_key_set
        else:
            train_keys = subset_keys
    elif subset_keys:
        train_keys = subset_keys
    else:
        train_keys = set()

    # SANITY: cap train and val to small clip counts from config
    if args.SANITY:
        sanity_train = cfg["data"]["sanity_train_clips"]
        sanity_val = cfg["data"]["sanity_val_clips"]
        if train_keys:
            train_keys = set(list(train_keys)[:sanity_train])
        else:
            local_data = cfg["data"].get("local_data")
            ds = _create_stream(0, local_data=local_data)
            collected = []
            for example in ds:
                collected.append(get_clip_key(example))
                if len(collected) >= sanity_train + sanity_val:
                    break
            train_keys = set(collected[:sanity_train])
            val_key_set = set(collected[sanity_train:sanity_train + sanity_val])
        if val_key_set:
            val_key_set = set(list(val_key_set)[:sanity_val])

    # Discover n_train: from subset, local manifest, or fail
    if train_keys:
        n_train = len(train_keys)
    else:
        # Full dataset: read clip count from local manifest
        local_data = cfg["data"].get("local_data")
        manifest_path = Path(local_data) / "manifest.json" if local_data else None
        if manifest_path and manifest_path.exists():
            manifest = json.load(open(manifest_path))
            n_total = manifest.get("n_clips", manifest.get("total_clips"))
            n_train = n_total - len(val_key_set)
            print(f"Dataset size from manifest: {n_total:,} total, {n_train:,} train "
                  f"({len(val_key_set)} val excluded)")
        else:
            print("FATAL: Cannot determine dataset size.")
            print("Provide --subset <file> or --local-data <dir> with manifest.json")
            sys.exit(1)
    batch_size = cfg["optimization"]["batch_size"]
    max_epochs = cfg["optimization"]["max_epochs"]
    steps_per_epoch = max(1, n_train // batch_size)
    total_steps = steps_per_epoch * max_epochs
    saves_per_epoch = cfg["checkpoint"]["saves_per_epoch"]
    ckpt_interval = max(1, steps_per_epoch // saves_per_epoch)
    keep_last_n = cfg["checkpoint"]["keep_last_n"]
    evals_per_epoch = cfg["validation"]["evals_per_epoch"]
    val_interval = max(1, steps_per_epoch // evals_per_epoch)

    print(f"Train clips: {n_train:,} | Val clips: {len(val_key_set):,}")
    print(f"Epochs: {max_epochs} | Steps/epoch: {steps_per_epoch:,} | Total steps: {total_steps:,}")
    print(f"Checkpoint every {ckpt_interval} steps ({saves_per_epoch}x/epoch, keep last {keep_last_n})")
    print(f"Validation every {val_interval} steps ({evals_per_epoch}x/epoch, {len(val_key_set)} val clips)")

    # Optimizer & scheduler (cosine over total_steps)
    optimizer = build_optimizer(student, predictor, cfg["optimization"])
    scheduler = build_scheduler(optimizer, cfg["optimization"], total_steps)
    mp_cfg = cfg["mixed_precision"]
    use_scaler = mp_cfg["enabled"] and mp_cfg["dtype"] == "float16"
    scaler = torch.amp.GradScaler("cuda", enabled=use_scaler)

    # Resume from checkpoint
    start_step = 0
    best_val_loss = float("inf")
    ckpt_path = output_dir / f"{CHECKPOINT_PREFIX}_latest.pt"
    if ckpt_path.exists():
        start_step, best_val_loss = load_training_checkpoint(
            ckpt_path, student, teacher, predictor, optimizer, scheduler, scaler)
        print(f"Resumed from step {start_step}, best val loss: {best_val_loss:.4f}")

    # ── Collect val clips into memory (from --val-subset, once before training) ──
    val_batches = []
    val_collected_keys = []

    if val_key_set:
        print(f"\nCollecting {len(val_key_set)} val clips into memory...")
        import tempfile as _tmpmod
        _val_tmp = _tmpmod.mkdtemp(prefix="m09_val_")
        # Use --val-local-data if provided, otherwise fall back to --local-data
        val_local = getattr(args, "val_local_data", None) or cfg["data"].get("local_data")
        _val_ds = _create_stream(0, local_data=val_local)
        _val_batch_buf = []
        for _ex in _val_ds:
            _ck = get_clip_key(_ex)
            if _ck not in val_key_set:
                continue
            _mp4 = _ex.get("mp4", b"")
            _mp4b = _mp4["bytes"] if isinstance(_mp4, dict) else _mp4
            if not _mp4b:
                continue
            _vt = decode_video_bytes(_mp4b, _val_tmp, _ck, cfg["data"]["num_frames"])
            if _vt is None:
                continue
            _aug = augment_clip_consistent(_vt, cfg.get("augmentation", {}), cfg["data"]["crop_size"])
            _val_batch_buf.append(_aug)
            val_collected_keys.append(_ck)
            if len(_val_batch_buf) >= batch_size:
                _batch = torch.stack(_val_batch_buf, dim=0).permute(0, 2, 1, 3, 4)
                val_batches.append(_batch)
                _val_batch_buf = []
            if len(val_collected_keys) >= len(val_key_set):
                break
        if _val_batch_buf:
            _batch = torch.stack(_val_batch_buf, dim=0).permute(0, 2, 1, 3, 4)
            val_batches.append(_batch)
        import shutil as _shutil
        _shutil.rmtree(_val_tmp, ignore_errors=True)
        print(f"Val clips collected: {len(val_collected_keys)} in {len(val_batches)} batches")
    else:
        print("No --val-subset provided — skipping validation during training")

    # Data stream (producer loops over epochs automatically)
    q = queue.Queue(maxsize=PREFETCH_QUEUE_SIZE)
    stop_event = threading.Event()
    prod = threading.Thread(
        target=producer_thread,
        args=(cfg, q, stop_event, train_keys, start_step),
        daemon=True,
    )
    prod.start()

    # WandB — include lambda in run name for ablation comparison
    mode = "SANITY" if args.SANITY else ("POC" if args.POC else "FULL")
    lam_val = cfg["drift_control"]["lambda_reg"]
    lam_tag = f"_lambda{f'{lam_val:g}'.replace('.', '_')}"
    wb_run = init_wandb("m09", f"{mode}{lam_tag}", config=cfg, enabled=not args.no_wandb)

    # Training config
    ema_momentum = cfg["optimization"]["ema_momentum"]
    loss_exp = cfg["optimization"]["loss_exp"]
    drift_cfg = cfg["drift_control"]
    dtype = getattr(torch, mp_cfg["dtype"])

    pbar = tqdm(total=total_steps, initial=start_step,
                desc="m09_pretrain", unit="step")

    # CSV loss log
    csv_path = output_dir / "loss_log.csv"
    csv_exists = csv_path.exists()
    csv_file = open(csv_path, "a", newline="")
    csv_writer = csv.writer(csv_file)
    if not csv_exists:
        csv_writer.writerow(["step", "epoch", "loss_jepa", "loss_drift", "loss_total",
                             "lr", "grad_norm", "throughput"])
        csv_file.flush()

    # Windowed throughput
    window_start = time.time()
    window_steps = 0
    running_loss = 0.0

    print(f"\n=== Training: {start_step} → {total_steps} steps ({max_epochs} epochs) ===")
    print(f"Batch size: {batch_size}")
    print(f"Grad checkpointing: {cfg['model'].get('use_activation_checkpointing', False)}")
    print(f"Mixed precision: {mp_cfg['dtype']}")
    print(f"EMA momentum: {ema_momentum}")
    print(f"Drift control: lambda={drift_cfg['lambda_reg'] if drift_cfg['enabled'] else 0}")
    print(f"Loss log: {csv_path}")

    step = start_step
    try:
        for step in range(start_step, total_steps):
            epoch = step // steps_per_epoch
            epoch_step = step % steps_per_epoch

            # Get batch from producer
            try:
                msg_type, batch_clips, batch_keys = q.get(timeout=600)
            except queue.Empty:
                print(f"\nProducer timeout at step {step}. Saving checkpoint...")
                break
            if msg_type == "done":
                print(f"\nData exhausted at step {step}.")
                break

            batch_clips = batch_clips.to(device)
            actual_bs = batch_clips.shape[0]

            # Generate masks
            all_masks_enc, all_masks_pred = [], []
            for mg in mask_generators:
                m_enc, m_pred = mg(actual_bs)
                all_masks_enc.append(m_enc.to(device))
                all_masks_pred.append(m_pred.to(device))

            # Forward pass (zero_grad after step, matching Meta's pattern)
            with torch.amp.autocast("cuda", dtype=dtype, enabled=mp_cfg["enabled"]):
                # Teacher: all tokens, no grad, layer_norm (matches Meta's train.py line 432)
                with torch.no_grad():
                    h = teacher(batch_clips)
                    h = F.layer_norm(h, (h.size(-1),))

                pred_features = []
                for i, (m_enc, m_pred) in enumerate(zip(all_masks_enc, all_masks_pred)):
                    z = student(batch_clips, masks=[m_enc])
                    p = predictor(z, [m_enc], [m_pred], mask_index=i)
                    pred_features.append(p)

                jepa_loss = compute_jepa_loss(pred_features, h, all_masks_pred, loss_exp)

                if drift_cfg["enabled"] and drift_cfg["lambda_reg"] > 0:
                    drift_loss = compute_drift_loss(student, init_params,
                                                    drift_cfg["lambda_reg"])
                    total_loss = jepa_loss + drift_loss
                else:
                    drift_loss = torch.tensor(0.0)
                    total_loss = jepa_loss

            # Backward + optimizer step
            scaler.scale(total_loss).backward()
            scaler.unscale_(optimizer)
            grad_norm = torch.nn.utils.clip_grad_norm_(
                list(student.parameters()) + list(predictor.parameters()),
                cfg["optimization"]["grad_clip"])
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad()
            scheduler.step()
            update_weight_decay(optimizer, cfg["optimization"], step, total_steps)

            # EMA teacher update
            update_teacher_ema(student, teacher, ema_momentum)

            # Periodic GC (every 50 steps, matches Meta's sync_gc pattern)
            if step % 50 == 0:
                gc.collect()

            # Per-step logging
            jepa_val = jepa_loss.item()
            drift_val = drift_loss.item()
            total_val = total_loss.item()
            lr_val = scheduler.get_last_lr()[0]
            gn_val = grad_norm.item() if torch.is_tensor(grad_norm) else grad_norm

            running_loss += total_val
            window_steps += 1
            now = time.time()
            window_elapsed = now - window_start
            throughput = window_steps / window_elapsed if window_elapsed > 0 else 0

            csv_writer.writerow([step, epoch, f"{jepa_val:.6f}", f"{drift_val:.6f}",
                                 f"{total_val:.6f}", f"{lr_val:.2e}",
                                 f"{gn_val:.4f}", f"{throughput:.2f}"])
            if step % 10 == 0:
                csv_file.flush()

            log_metrics(wb_run, {
                "loss/jepa": jepa_val,
                "loss/drift": drift_val,
                "loss/total": total_val,
                "lr": lr_val,
                "grad_norm": gn_val,
                "epoch": epoch,
                "throughput_steps_per_s": throughput,
            }, step=step)

            if window_elapsed >= 30:
                pbar.set_postfix_str(
                    f"E{epoch} loss={running_loss/window_steps:.4f} "
                    f"drift={drift_val:.4f} "
                    f"lr={lr_val:.2e} "
                    f"grad={gn_val:.2f} "
                    f"{throughput:.2f} step/s")
                window_start = now
                window_steps = 0
                running_loss = 0.0

            pbar.update(1)

            # Periodic checkpoint (every ckpt_interval steps)
            if (step + 1) % ckpt_interval == 0:
                pct = (epoch_step + 1) / steps_per_epoch * 100
                print(f"\n--- Checkpoint at {pct:.0f}% of epoch {epoch + 1} (step {step + 1}) ---")
                save_training_checkpoint(
                    output_dir / f"{CHECKPOINT_PREFIX}_step{step+1}.pt",
                    student, teacher, predictor, optimizer, scheduler, scaler,
                    step + 1, best_val_loss, full=False)
                save_training_checkpoint(
                    ckpt_path, student, teacher, predictor, optimizer, scheduler,
                    scaler, step + 1, best_val_loss, full=True)
                cleanup_old_checkpoints(output_dir, keep_n=keep_last_n)

            # Periodic validation (every val_interval steps)
            if (step + 1) % val_interval == 0 and val_batches:
                pct = (epoch_step + 1) / steps_per_epoch * 100
                val_loss = run_validation(
                    student, teacher, predictor, mask_generators,
                    val_batches, cfg, device, step + 1)
                log_metrics(wb_run, {
                    "val/jepa_loss": val_loss,
                    "val/epoch_pct": pct,
                }, step=step)

                # Best model selection by lowest val loss
                if val_loss < best_val_loss:
                    best_val_loss = val_loss
                    save_training_checkpoint(
                        output_dir / f"{CHECKPOINT_PREFIX}_best.pt",
                        student, teacher, predictor, optimizer, scheduler,
                        scaler, step + 1, best_val_loss, full=False)
                    print(f"  New best val loss: {best_val_loss:.4f}")

            # End-of-epoch logging
            if epoch_step == steps_per_epoch - 1:
                print(f"\n--- Epoch {epoch + 1}/{max_epochs} complete (step {step + 1}) ---")
                log_metrics(wb_run, {"epoch_complete": epoch + 1}, step=step)

    except KeyboardInterrupt:
        print("\nInterrupted! Saving checkpoint...")
    finally:
        pbar.close()
        csv_file.close()
        stop_event.set()
        gc.enable()  # re-enable auto GC

    # Export student encoder (the only deliverable)
    export_student_for_eval(student, student_path)

    # Cleanup ALL checkpoints — student_encoder.pt is the deliverable
    for ckpt_file in output_dir.glob(f"{CHECKPOINT_PREFIX}_*.pt"):
        ckpt_file.unlink()
        print(f"  Cleaned: {ckpt_file.name}")

    # Save training summary as JSON (for winner selection, not stdout parsing)
    total_epochs_done = (step + 1) / max(steps_per_epoch, 1)
    summary = {
        "steps": step + 1,
        "epochs": round(total_epochs_done, 2),
        "clips_seen": (step + 1) * batch_size,
        "final_jepa_loss": jepa_val,
        "final_drift_loss": drift_val,
        "final_total_loss": total_val,
        "final_lr": lr_val,
        "final_grad_norm": gn_val,
        "lambda_reg": drift_cfg["lambda_reg"],
        "batch_size": batch_size,
    }
    summary_path = output_dir / "training_summary.json"
    with open(summary_path, "w") as f:
        json.dump(summary, f, indent=2)

    finish_wandb(wb_run)
    print(f"\n=== TRAINING COMPLETE ===")
    print(f"Steps:        {step + 1} ({total_epochs_done:.1f} epochs)")
    print(f"Clips seen:   {(step + 1) * batch_size:,}")
    print(f"Student:      {student_path}")
    print(f"Loss log:     {csv_path}")
    print(f"Summary:      {summary_path}")


# ═════════════════════════════════════════════════════════════════════════
# MAIN
# ═════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description="V-JEPA 2 continual pretraining on Indian urban clips (Ch10)")
    parser.add_argument("--config", type=str, default=DEFAULT_CONFIG,
                        help="YAML config path")
    parser.add_argument("--SANITY", action="store_true",
                        help="Quick validation: 50 steps, batch_size=2")
    parser.add_argument("--POC", action="store_true",
                        help="POC subset (~10K clips, 5 epochs)")
    parser.add_argument("--FULL", action="store_true",
                        help="Full training run")
    parser.add_argument("--batch-size", type=int, default=None,
                        help="Override batch size from config")
    parser.add_argument("--lambda-reg", type=float, default=None,
                        help="Override drift control lambda (ablation: 0, 0.001, 0.01, 0.1)")
    parser.add_argument("--max-epochs", type=int, default=None,
                        help="Override max epochs (SANITY=1, --POC=5, --FULL=1)")
    parser.add_argument("--val-subset", type=str, default=None,
                        help="Path to val subset JSON (e.g., data/val_1k.json). "
                             "These clips are excluded from training and used for periodic val loss.")
    parser.add_argument("--val-local-data", type=str, default=None,
                        help="Local WebDataset dir for val clips (e.g., data/val_1k_local). "
                             "If omitted, val clips are loaded from --local-data.")
    add_subset_arg(parser)
    add_local_data_arg(parser)
    add_wandb_args(parser)
    args = parser.parse_args()

    if not (args.SANITY or args.POC or args.FULL):
        parser.print_help()
        print("\nERROR: Specify --SANITY, --POC, or --FULL")
        sys.exit(1)

    ensure_local_data(args)

    cfg = load_config(args.config)
    cfg = merge_config_with_args(cfg, args)

    train(cfg, args)


if __name__ == "__main__":
    main()
